/**
 * Auth Test Data Seeder
 * Seeds and cleans up test users for E2E testing
 *
 * Generated by Test Builder Agent
 * Date: 2025-12-16
 *
 * Usage:
 *   npx ts-node tests/fixtures/seeders/authSeeder.ts seed
 *   npx ts-node tests/fixtures/seeders/authSeeder.ts cleanup
 */

import { createClient } from '@supabase/supabase-js'

// E2E test user credentials
export const E2E_TEST_USER = {
  email: 'e2e-test@familymealplanner.com',
  password: 'E2ETestPassword123!',
  name: 'E2E Test User',
}

// Supabase client for admin operations
const getSupabaseAdmin = () => {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error(
      'Missing Supabase credentials. Ensure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.'
    )
  }

  return createClient(supabaseUrl, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  })
}

// ============================================================================
// SEED FUNCTIONS
// ============================================================================

/**
 * Seeds the E2E test user if it doesn't exist
 * @returns The created/existing user or null if failed
 */
export async function seedTestUser(): Promise<{ id: string; email: string } | null> {
  console.log('Seeding E2E test user...')

  try {
    const supabase = getSupabaseAdmin()

    // Check if user already exists
    const { data: existingUsers } = await supabase.auth.admin.listUsers()
    const existingUser = existingUsers?.users.find((u) => u.email === E2E_TEST_USER.email)

    if (existingUser) {
      console.log('E2E test user already exists:', existingUser.id)
      return { id: existingUser.id, email: existingUser.email! }
    }

    // Create auth user
    const { data: authUser, error: authError } = await supabase.auth.admin.createUser({
      email: E2E_TEST_USER.email,
      password: E2E_TEST_USER.password,
      email_confirm: true,
      user_metadata: {
        name: E2E_TEST_USER.name,
      },
    })

    if (authError) {
      console.error('Failed to create auth user:', authError.message)
      return null
    }

    // Create profile record
    const { error: profileError } = await supabase.from('Profile').insert({
      id: `profile-${authUser.user.id}`,
      userId: authUser.user.id,
      profileName: E2E_TEST_USER.name,
      age: 35,
      gender: 'male',
      heightCm: 180,
      currentWeightKg: 80,
      activityLevel: 'moderate',
      dailyCalorieTarget: 2200,
      dailyProteinTarget: 170,
      dailyCarbsTarget: 200,
      dailyFatTarget: 70,
      dailyFiberTarget: 35,
      macroTrackingEnabled: true,
    })

    if (profileError) {
      console.warn('Warning: Failed to create profile:', profileError.message)
      // Don't fail - user can still be used for auth tests
    }

    console.log('E2E test user created:', authUser.user.id)
    return { id: authUser.user.id, email: authUser.user.email! }
  } catch (error) {
    console.error('Error seeding test user:', error)
    return null
  }
}

/**
 * Seeds test recipes for the E2E test user
 */
export async function seedTestRecipes(userId: string): Promise<number> {
  console.log('Seeding test recipes for user:', userId)

  try {
    const supabase = getSupabaseAdmin()

    const testRecipes = [
      {
        userId,
        recipeName: 'E2E Test Chicken Stir Fry',
        description: 'A quick and healthy test recipe',
        servings: 4,
        prepTimeMinutes: 15,
        cookTimeMinutes: 20,
        totalTimeMinutes: 35,
        cuisineType: 'Asian',
        caloriesPerServing: 450,
        proteinPerServing: 35,
        carbsPerServing: 30,
        fatPerServing: 18,
        recipeSource: 'manual',
        isActive: true,
      },
      {
        userId,
        recipeName: 'E2E Test Pasta Bolognese',
        description: 'Classic Italian pasta dish',
        servings: 4,
        prepTimeMinutes: 20,
        cookTimeMinutes: 45,
        totalTimeMinutes: 65,
        cuisineType: 'Italian',
        caloriesPerServing: 520,
        proteinPerServing: 28,
        carbsPerServing: 55,
        fatPerServing: 22,
        recipeSource: 'manual',
        isActive: true,
      },
      {
        userId,
        recipeName: 'E2E Test Vegetable Curry',
        description: 'Vegetarian curry with mixed vegetables',
        servings: 4,
        prepTimeMinutes: 15,
        cookTimeMinutes: 30,
        totalTimeMinutes: 45,
        cuisineType: 'Indian',
        isVegetarian: true,
        caloriesPerServing: 380,
        proteinPerServing: 12,
        carbsPerServing: 45,
        fatPerServing: 18,
        recipeSource: 'manual',
        isActive: true,
      },
    ]

    const { data, error } = await supabase.from('Recipe').insert(testRecipes).select()

    if (error) {
      console.error('Failed to seed recipes:', error.message)
      return 0
    }

    console.log(`Seeded ${data?.length || 0} test recipes`)
    return data?.length || 0
  } catch (error) {
    console.error('Error seeding recipes:', error)
    return 0
  }
}

// ============================================================================
// CLEANUP FUNCTIONS
// ============================================================================

/**
 * Cleans up a specific test user and all their data
 */
export async function cleanupTestUser(email: string): Promise<boolean> {
  console.log('Cleaning up test user:', email)

  try {
    const supabase = getSupabaseAdmin()

    // Find user by email
    const { data: users } = await supabase.auth.admin.listUsers()
    const user = users?.users.find((u) => u.email === email)

    if (!user) {
      console.log('User not found:', email)
      return true
    }

    // Delete user's data in order (respecting foreign keys)
    const tables = [
      'ShoppingListItem',
      'ShoppingList',
      'Meal',
      'MealPlan',
      'RecipeIngredient',
      'Recipe',
      'InventoryItem',
      'Staple',
      'Profile',
    ]

    for (const table of tables) {
      const { error } = await supabase.from(table).delete().eq('userId', user.id)
      if (error) {
        console.warn(`Warning: Failed to delete from ${table}:`, error.message)
      }
    }

    // Delete auth user
    const { error: deleteError } = await supabase.auth.admin.deleteUser(user.id)
    if (deleteError) {
      console.error('Failed to delete auth user:', deleteError.message)
      return false
    }

    console.log('User cleaned up:', email)
    return true
  } catch (error) {
    console.error('Error cleaning up user:', error)
    return false
  }
}

/**
 * Cleans up ALL test data (users with test- or e2e- prefix)
 */
export async function cleanupAllTestData(): Promise<{ users: number; success: boolean }> {
  console.log('Cleaning up all test data...')

  try {
    const supabase = getSupabaseAdmin()

    // Find all test users
    const { data: users } = await supabase.auth.admin.listUsers()
    const testUsers =
      users?.users.filter(
        (u) => u.email?.startsWith('test') || u.email?.startsWith('e2e') || u.email?.includes('@test.')
      ) || []

    console.log(`Found ${testUsers.length} test users to clean up`)

    let cleanedUp = 0
    for (const user of testUsers) {
      const success = await cleanupTestUser(user.email!)
      if (success) cleanedUp++
    }

    console.log(`Cleaned up ${cleanedUp}/${testUsers.length} test users`)
    return { users: cleanedUp, success: cleanedUp === testUsers.length }
  } catch (error) {
    console.error('Error cleaning up test data:', error)
    return { users: 0, success: false }
  }
}

/**
 * Cleans up test recipes created during E2E tests
 */
export async function cleanupTestRecipes(): Promise<number> {
  console.log('Cleaning up test recipes...')

  try {
    const supabase = getSupabaseAdmin()

    // Delete recipes with "E2E Test" prefix
    const { data, error } = await supabase
      .from('Recipe')
      .delete()
      .like('recipeName', 'E2E Test%')
      .select()

    if (error) {
      console.error('Failed to cleanup recipes:', error.message)
      return 0
    }

    console.log(`Cleaned up ${data?.length || 0} test recipes`)
    return data?.length || 0
  } catch (error) {
    console.error('Error cleaning up recipes:', error)
    return 0
  }
}

// ============================================================================
// CLI RUNNER
// ============================================================================

async function main() {
  const command = process.argv[2]

  switch (command) {
    case 'seed': {
      const user = await seedTestUser()
      if (user) {
        await seedTestRecipes(user.id)
      }
      process.exit(user ? 0 : 1)
      break
    }

    case 'cleanup': {
      const result = await cleanupAllTestData()
      await cleanupTestRecipes()
      process.exit(result.success ? 0 : 1)
      break
    }

    case 'cleanup-user': {
      const email = process.argv[3]
      if (!email) {
        console.error('Usage: cleanup-user <email>')
        process.exit(1)
      }
      const success = await cleanupTestUser(email)
      process.exit(success ? 0 : 1)
      break
    }

    default:
      console.log(`
Auth Test Data Seeder

Usage:
  npx ts-node tests/fixtures/seeders/authSeeder.ts <command>

Commands:
  seed            Create E2E test user and sample recipes
  cleanup         Remove all test users and data
  cleanup-user    Remove specific user: cleanup-user <email>

Environment Variables Required:
  NEXT_PUBLIC_SUPABASE_URL      - Supabase project URL
  SUPABASE_SERVICE_ROLE_KEY     - Service role key (admin access)
      `)
      process.exit(1)
  }
}

// Run if executed directly
if (require.main === module) {
  main()
}
