/**
 * Recipe Test Data Seeder
 * Seeds and cleans up test recipes for E2E testing
 *
 * Generated by Test Builder Agent
 * Date: 2025-12-16
 *
 * Usage:
 *   npx ts-node tests/fixtures/seeders/recipeSeeder.ts seed <userId>
 *   npx ts-node tests/fixtures/seeders/recipeSeeder.ts cleanup
 */

import { createClient } from '@supabase/supabase-js'

// Test recipe prefix for easy identification and cleanup
const TEST_PREFIX = 'E2E Test'

// Supabase client for admin operations
const getSupabaseAdmin = () => {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error(
      'Missing Supabase credentials. Ensure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.'
    )
  }

  return createClient(supabaseUrl, serviceRoleKey)
}

// ============================================================================
// TEST RECIPE DATA
// ============================================================================

const testRecipeData = [
  {
    recipeName: `${TEST_PREFIX} Chicken Stir Fry`,
    description: 'Quick and healthy Asian-style chicken',
    servings: 4,
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    totalTimeMinutes: 35,
    cuisineType: 'Asian',
    mealType: ['dinner'],
    caloriesPerServing: 450,
    proteinPerServing: 35,
    carbsPerServing: 30,
    fatPerServing: 18,
    fiberPerServing: 5,
    isVegetarian: false,
    isVegan: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNutFree: true,
    tags: ['quick', 'healthy', 'high-protein'],
    recipeSource: 'manual',
    isActive: true,
  },
  {
    recipeName: `${TEST_PREFIX} Beef Tacos`,
    description: 'Mexican-style beef tacos with fresh toppings',
    servings: 4,
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    totalTimeMinutes: 35,
    cuisineType: 'Mexican',
    mealType: ['dinner'],
    caloriesPerServing: 520,
    proteinPerServing: 28,
    carbsPerServing: 45,
    fatPerServing: 24,
    fiberPerServing: 4,
    isVegetarian: false,
    isVegan: false,
    isDairyFree: false,
    isGlutenFree: false,
    isNutFree: true,
    tags: ['mexican', 'family-friendly'],
    recipeSource: 'manual',
    isActive: true,
  },
  {
    recipeName: `${TEST_PREFIX} Vegetable Curry`,
    description: 'Creamy vegetarian curry with mixed vegetables',
    servings: 4,
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    totalTimeMinutes: 45,
    cuisineType: 'Indian',
    mealType: ['dinner'],
    caloriesPerServing: 380,
    proteinPerServing: 12,
    carbsPerServing: 45,
    fatPerServing: 18,
    fiberPerServing: 8,
    isVegetarian: true,
    isVegan: false,
    isDairyFree: false,
    isGlutenFree: true,
    isNutFree: false,
    tags: ['vegetarian', 'curry', 'comfort-food'],
    recipeSource: 'manual',
    isActive: true,
  },
  {
    recipeName: `${TEST_PREFIX} Salmon Pasta`,
    description: 'Creamy salmon pasta with dill',
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    totalTimeMinutes: 35,
    cuisineType: 'Italian',
    mealType: ['dinner'],
    caloriesPerServing: 580,
    proteinPerServing: 32,
    carbsPerServing: 55,
    fatPerServing: 26,
    fiberPerServing: 3,
    isVegetarian: false,
    isVegan: false,
    isDairyFree: false,
    isGlutenFree: false,
    isNutFree: true,
    tags: ['pasta', 'fish', 'quick'],
    recipeSource: 'manual',
    isActive: true,
  },
  {
    recipeName: `${TEST_PREFIX} Mediterranean Salad`,
    description: 'Fresh Greek-style salad with feta',
    servings: 2,
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    totalTimeMinutes: 15,
    cuisineType: 'Mediterranean',
    mealType: ['lunch'],
    caloriesPerServing: 320,
    proteinPerServing: 12,
    carbsPerServing: 18,
    fatPerServing: 24,
    fiberPerServing: 6,
    isVegetarian: true,
    isVegan: false,
    isDairyFree: false,
    isGlutenFree: true,
    isNutFree: true,
    tags: ['salad', 'healthy', 'no-cook'],
    recipeSource: 'manual',
    isActive: true,
  },
  {
    recipeName: `${TEST_PREFIX} Overnight Oats`,
    description: 'Easy breakfast with berries and honey',
    servings: 1,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    totalTimeMinutes: 5,
    cuisineType: 'British',
    mealType: ['breakfast'],
    caloriesPerServing: 380,
    proteinPerServing: 15,
    carbsPerServing: 55,
    fatPerServing: 12,
    fiberPerServing: 8,
    isVegetarian: true,
    isVegan: false,
    isDairyFree: false,
    isGlutenFree: false,
    isNutFree: false,
    tags: ['breakfast', 'meal-prep', 'healthy'],
    recipeSource: 'manual',
    isActive: true,
  },
  {
    recipeName: `${TEST_PREFIX} Batch Cook Chili`,
    description: 'Large batch chili perfect for freezing',
    servings: 8,
    prepTimeMinutes: 20,
    cookTimeMinutes: 90,
    totalTimeMinutes: 110,
    cuisineType: 'American',
    mealType: ['dinner'],
    caloriesPerServing: 420,
    proteinPerServing: 28,
    carbsPerServing: 35,
    fatPerServing: 18,
    fiberPerServing: 10,
    isVegetarian: false,
    isVegan: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNutFree: true,
    tags: ['batch-cook', 'freezer-friendly', 'meal-prep'],
    recipeSource: 'manual',
    isActive: true,
  },
  {
    recipeName: `${TEST_PREFIX} Tofu Stir Fry`,
    description: 'Vegan protein-rich stir fry',
    servings: 4,
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    totalTimeMinutes: 35,
    cuisineType: 'Asian',
    mealType: ['dinner'],
    caloriesPerServing: 350,
    proteinPerServing: 22,
    carbsPerServing: 28,
    fatPerServing: 18,
    fiberPerServing: 6,
    isVegetarian: true,
    isVegan: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNutFree: true,
    tags: ['vegan', 'plant-based', 'high-protein'],
    recipeSource: 'manual',
    isActive: true,
  },
]

const testIngredientData = {
  [`${TEST_PREFIX} Chicken Stir Fry`]: [
    { ingredientName: 'Chicken Breast', quantity: 500, unit: 'g', sortOrder: 1 },
    { ingredientName: 'Soy Sauce', quantity: 3, unit: 'tbsp', sortOrder: 2 },
    { ingredientName: 'Sesame Oil', quantity: 1, unit: 'tbsp', sortOrder: 3 },
    { ingredientName: 'Mixed Vegetables', quantity: 400, unit: 'g', sortOrder: 4 },
    { ingredientName: 'Garlic', quantity: 3, unit: 'clove', sortOrder: 5 },
    { ingredientName: 'Ginger', quantity: 1, unit: 'tbsp', sortOrder: 6 },
  ],
  [`${TEST_PREFIX} Beef Tacos`]: [
    { ingredientName: 'Beef Mince', quantity: 500, unit: 'g', sortOrder: 1 },
    { ingredientName: 'Taco Seasoning', quantity: 2, unit: 'tbsp', sortOrder: 2 },
    { ingredientName: 'Soft Tortillas', quantity: 8, unit: 'piece', sortOrder: 3 },
    { ingredientName: 'Lettuce', quantity: 100, unit: 'g', sortOrder: 4 },
    { ingredientName: 'Cheese', quantity: 100, unit: 'g', sortOrder: 5 },
    { ingredientName: 'Sour Cream', quantity: 100, unit: 'ml', sortOrder: 6 },
  ],
  [`${TEST_PREFIX} Vegetable Curry`]: [
    { ingredientName: 'Mixed Vegetables', quantity: 600, unit: 'g', sortOrder: 1 },
    { ingredientName: 'Coconut Milk', quantity: 400, unit: 'ml', sortOrder: 2 },
    { ingredientName: 'Curry Paste', quantity: 3, unit: 'tbsp', sortOrder: 3 },
    { ingredientName: 'Onion', quantity: 1, unit: 'piece', sortOrder: 4 },
    { ingredientName: 'Garlic', quantity: 3, unit: 'clove', sortOrder: 5 },
    { ingredientName: 'Rice', quantity: 300, unit: 'g', sortOrder: 6 },
  ],
}

// ============================================================================
// SEED FUNCTIONS
// ============================================================================

/**
 * Seeds test recipes for a specific user
 */
export async function seedTestRecipes(userId: string): Promise<{ recipes: number; ingredients: number }> {
  console.log('Seeding test recipes for user:', userId)

  try {
    const supabase = getSupabaseAdmin()
    let recipeCount = 0
    let ingredientCount = 0

    for (const recipeData of testRecipeData) {
      // Insert recipe
      const { data: recipe, error: recipeError } = await supabase
        .from('Recipe')
        .insert({
          ...recipeData,
          userId,
        })
        .select()
        .single()

      if (recipeError) {
        console.warn(`Warning: Failed to insert recipe ${recipeData.recipeName}:`, recipeError.message)
        continue
      }

      recipeCount++

      // Insert ingredients if we have them
      const ingredients = testIngredientData[recipeData.recipeName]
      if (ingredients && recipe) {
        const { data: insertedIngredients, error: ingError } = await supabase
          .from('RecipeIngredient')
          .insert(
            ingredients.map((ing) => ({
              ...ing,
              recipeId: recipe.id,
            }))
          )
          .select()

        if (ingError) {
          console.warn(`Warning: Failed to insert ingredients for ${recipeData.recipeName}:`, ingError.message)
        } else {
          ingredientCount += insertedIngredients?.length || 0
        }
      }
    }

    console.log(`Seeded ${recipeCount} recipes with ${ingredientCount} ingredients`)
    return { recipes: recipeCount, ingredients: ingredientCount }
  } catch (error) {
    console.error('Error seeding recipes:', error)
    return { recipes: 0, ingredients: 0 }
  }
}

/**
 * Seeds minimal recipes (just enough for meal plan generation tests)
 */
export async function seedMinimalRecipes(userId: string, count: number = 10): Promise<number> {
  console.log(`Seeding ${count} minimal recipes for user:`, userId)

  try {
    const supabase = getSupabaseAdmin()

    const minimalRecipes = Array.from({ length: count }, (_, i) => ({
      userId,
      recipeName: `${TEST_PREFIX} Recipe ${i + 1}`,
      description: `Test recipe number ${i + 1}`,
      servings: 4,
      prepTimeMinutes: 15,
      cookTimeMinutes: 30,
      totalTimeMinutes: 45,
      cuisineType: ['Italian', 'Asian', 'Mexican', 'British', 'Indian'][i % 5],
      caloriesPerServing: 400 + i * 20,
      proteinPerServing: 25 + i * 2,
      carbsPerServing: 40 + i * 3,
      fatPerServing: 15 + i,
      recipeSource: 'manual',
      isActive: true,
    }))

    const { data, error } = await supabase.from('Recipe').insert(minimalRecipes).select()

    if (error) {
      console.error('Failed to seed minimal recipes:', error.message)
      return 0
    }

    console.log(`Seeded ${data?.length || 0} minimal recipes`)
    return data?.length || 0
  } catch (error) {
    console.error('Error seeding minimal recipes:', error)
    return 0
  }
}

// ============================================================================
// CLEANUP FUNCTIONS
// ============================================================================

/**
 * Cleans up all test recipes (those with E2E Test prefix)
 */
export async function cleanupTestRecipes(): Promise<{ recipes: number; ingredients: number }> {
  console.log('Cleaning up test recipes...')

  try {
    const supabase = getSupabaseAdmin()

    // Find test recipes
    const { data: recipes, error: findError } = await supabase
      .from('Recipe')
      .select('id')
      .like('recipeName', `${TEST_PREFIX}%`)

    if (findError) {
      console.error('Failed to find test recipes:', findError.message)
      return { recipes: 0, ingredients: 0 }
    }

    if (!recipes || recipes.length === 0) {
      console.log('No test recipes to clean up')
      return { recipes: 0, ingredients: 0 }
    }

    const recipeIds = recipes.map((r) => r.id)

    // Delete ingredients first (foreign key)
    const { data: deletedIngredients, error: ingError } = await supabase
      .from('RecipeIngredient')
      .delete()
      .in('recipeId', recipeIds)
      .select()

    if (ingError) {
      console.warn('Warning: Failed to delete ingredients:', ingError.message)
    }

    // Delete recipes
    const { data: deletedRecipes, error: recipeError } = await supabase
      .from('Recipe')
      .delete()
      .in('id', recipeIds)
      .select()

    if (recipeError) {
      console.error('Failed to delete recipes:', recipeError.message)
      return { recipes: 0, ingredients: deletedIngredients?.length || 0 }
    }

    console.log(
      `Cleaned up ${deletedRecipes?.length || 0} recipes and ${deletedIngredients?.length || 0} ingredients`
    )
    return {
      recipes: deletedRecipes?.length || 0,
      ingredients: deletedIngredients?.length || 0,
    }
  } catch (error) {
    console.error('Error cleaning up recipes:', error)
    return { recipes: 0, ingredients: 0 }
  }
}

/**
 * Cleans up recipes for a specific user
 */
export async function cleanupUserRecipes(userId: string): Promise<number> {
  console.log('Cleaning up recipes for user:', userId)

  try {
    const supabase = getSupabaseAdmin()

    // Find user's test recipes
    const { data: recipes } = await supabase
      .from('Recipe')
      .select('id')
      .eq('userId', userId)
      .like('recipeName', `${TEST_PREFIX}%`)

    if (!recipes || recipes.length === 0) {
      console.log('No test recipes to clean up for user')
      return 0
    }

    const recipeIds = recipes.map((r) => r.id)

    // Delete ingredients
    await supabase.from('RecipeIngredient').delete().in('recipeId', recipeIds)

    // Delete recipes
    const { data: deleted } = await supabase.from('Recipe').delete().in('id', recipeIds).select()

    console.log(`Cleaned up ${deleted?.length || 0} recipes for user`)
    return deleted?.length || 0
  } catch (error) {
    console.error('Error cleaning up user recipes:', error)
    return 0
  }
}

// ============================================================================
// CLI RUNNER
// ============================================================================

async function main() {
  const command = process.argv[2]
  const arg = process.argv[3]

  switch (command) {
    case 'seed': {
      if (!arg) {
        console.error('Usage: seed <userId>')
        process.exit(1)
      }
      const result = await seedTestRecipes(arg)
      process.exit(result.recipes > 0 ? 0 : 1)
      break
    }

    case 'seed-minimal': {
      if (!arg) {
        console.error('Usage: seed-minimal <userId> [count]')
        process.exit(1)
      }
      const count = parseInt(process.argv[4] || '10', 10)
      const seeded = await seedMinimalRecipes(arg, count)
      process.exit(seeded > 0 ? 0 : 1)
      break
    }

    case 'cleanup': {
      const result = await cleanupTestRecipes()
      process.exit(result.recipes >= 0 ? 0 : 1)
      break
    }

    case 'cleanup-user': {
      if (!arg) {
        console.error('Usage: cleanup-user <userId>')
        process.exit(1)
      }
      const cleaned = await cleanupUserRecipes(arg)
      process.exit(cleaned >= 0 ? 0 : 1)
      break
    }

    default:
      console.log(`
Recipe Test Data Seeder

Usage:
  npx ts-node tests/fixtures/seeders/recipeSeeder.ts <command> [args]

Commands:
  seed <userId>                  Seed full test recipes for a user
  seed-minimal <userId> [count]  Seed minimal recipes (default: 10)
  cleanup                        Remove all test recipes
  cleanup-user <userId>          Remove test recipes for specific user

Environment Variables Required:
  NEXT_PUBLIC_SUPABASE_URL      - Supabase project URL
  SUPABASE_SERVICE_ROLE_KEY     - Service role key (admin access)
      `)
      process.exit(1)
  }
}

// Run if executed directly
if (require.main === module) {
  main()
}
