/**
 * Category Lookup Table for Shopping List Items
 *
 * This provides a deterministic lookup for common grocery items,
 * with AI as a fallback for items not in the list.
 */

// Comprehensive lookup table mapping normalized item names to categories
// Using UK supermarket conventions
export const CATEGORY_LOOKUP: Record<string, string> = {
  // ===== FRESH PRODUCE =====
  // Vegetables
  'onion': 'Fresh Produce',
  'onions': 'Fresh Produce',
  'red onion': 'Fresh Produce',
  'white onion': 'Fresh Produce',
  'spring onion': 'Fresh Produce',
  'spring onions': 'Fresh Produce',
  'scallion': 'Fresh Produce',
  'scallions': 'Fresh Produce',
  'shallot': 'Fresh Produce',
  'shallots': 'Fresh Produce',
  'leek': 'Fresh Produce',
  'leeks': 'Fresh Produce',
  'garlic': 'Fresh Produce',
  'garlic clove': 'Fresh Produce',
  'garlic cloves': 'Fresh Produce',
  'ginger': 'Fresh Produce',
  'fresh ginger': 'Fresh Produce',
  'root ginger': 'Fresh Produce',
  'fresh root ginger': 'Fresh Produce',
  'carrot': 'Fresh Produce',
  'carrots': 'Fresh Produce',
  'potato': 'Fresh Produce',
  'potatoes': 'Fresh Produce',
  'sweet potato': 'Fresh Produce',
  'sweet potatoes': 'Fresh Produce',
  'parsnip': 'Fresh Produce',
  'parsnips': 'Fresh Produce',
  'turnip': 'Fresh Produce',
  'turnips': 'Fresh Produce',
  'swede': 'Fresh Produce',
  'beetroot': 'Fresh Produce',
  'celery': 'Fresh Produce',
  'celery stalk': 'Fresh Produce',
  'celery stalks': 'Fresh Produce',
  'cucumber': 'Fresh Produce',
  'courgette': 'Fresh Produce',
  'courgettes': 'Fresh Produce',
  'zucchini': 'Fresh Produce',
  'aubergine': 'Fresh Produce',
  'eggplant': 'Fresh Produce',
  'tomato': 'Fresh Produce',
  'tomatoes': 'Fresh Produce',
  'cherry tomato': 'Fresh Produce',
  'cherry tomatoes': 'Fresh Produce',
  'plum tomato': 'Fresh Produce',
  'plum tomatoes': 'Fresh Produce',
  'vine tomato': 'Fresh Produce',
  'vine tomatoes': 'Fresh Produce',
  'pepper': 'Fresh Produce',
  'peppers': 'Fresh Produce',
  'bell pepper': 'Fresh Produce',
  'bell peppers': 'Fresh Produce',
  'red pepper': 'Fresh Produce',
  'green pepper': 'Fresh Produce',
  'yellow pepper': 'Fresh Produce',
  'orange pepper': 'Fresh Produce',
  'red bell pepper': 'Fresh Produce',
  'green bell pepper': 'Fresh Produce',
  'yellow bell pepper': 'Fresh Produce',
  'chilli': 'Fresh Produce',
  'chillies': 'Fresh Produce',
  'chili': 'Fresh Produce',
  'chilies': 'Fresh Produce',
  'red chilli': 'Fresh Produce',
  'green chilli': 'Fresh Produce',
  'jalapeno': 'Fresh Produce',
  'jalapenos': 'Fresh Produce',
  'scotch bonnet': 'Fresh Produce',
  'habanero': 'Fresh Produce',
  'mushroom': 'Fresh Produce',
  'mushrooms': 'Fresh Produce',
  'button mushroom': 'Fresh Produce',
  'button mushrooms': 'Fresh Produce',
  'chestnut mushroom': 'Fresh Produce',
  'chestnut mushrooms': 'Fresh Produce',
  'portobello mushroom': 'Fresh Produce',
  'shiitake mushroom': 'Fresh Produce',
  'shiitake mushrooms': 'Fresh Produce',
  'spinach': 'Fresh Produce',
  'baby spinach': 'Fresh Produce',
  'kale': 'Fresh Produce',
  'cavolo nero': 'Fresh Produce',
  'chard': 'Fresh Produce',
  'swiss chard': 'Fresh Produce',
  'lettuce': 'Fresh Produce',
  'iceberg lettuce': 'Fresh Produce',
  'romaine lettuce': 'Fresh Produce',
  'cos lettuce': 'Fresh Produce',
  'little gem lettuce': 'Fresh Produce',
  'rocket': 'Fresh Produce',
  'arugula': 'Fresh Produce',
  'watercress': 'Fresh Produce',
  'cabbage': 'Fresh Produce',
  'red cabbage': 'Fresh Produce',
  'white cabbage': 'Fresh Produce',
  'savoy cabbage': 'Fresh Produce',
  'pak choi': 'Fresh Produce',
  'bok choy': 'Fresh Produce',
  'chinese cabbage': 'Fresh Produce',
  'broccoli': 'Fresh Produce',
  'tenderstem broccoli': 'Fresh Produce',
  'purple sprouting broccoli': 'Fresh Produce',
  'cauliflower': 'Fresh Produce',
  'brussels sprout': 'Fresh Produce',
  'brussels sprouts': 'Fresh Produce',
  'asparagus': 'Fresh Produce',
  'green bean': 'Fresh Produce',
  'green beans': 'Fresh Produce',
  'french bean': 'Fresh Produce',
  'french beans': 'Fresh Produce',
  'runner bean': 'Fresh Produce',
  'runner beans': 'Fresh Produce',
  'broad bean': 'Fresh Produce',
  'broad beans': 'Fresh Produce',
  'mangetout': 'Fresh Produce',
  'sugar snap pea': 'Fresh Produce',
  'sugar snap peas': 'Fresh Produce',
  'pea': 'Fresh Produce',
  'peas': 'Fresh Produce',
  'garden peas': 'Fresh Produce',
  'sweetcorn': 'Fresh Produce',
  'corn on the cob': 'Fresh Produce',
  'baby corn': 'Fresh Produce',
  'radish': 'Fresh Produce',
  'radishes': 'Fresh Produce',
  'fennel': 'Fresh Produce',
  'artichoke': 'Fresh Produce',
  'globe artichoke': 'Fresh Produce',
  'bean sprout': 'Fresh Produce',
  'bean sprouts': 'Fresh Produce',
  'beansprouts': 'Fresh Produce',
  'avocado': 'Fresh Produce',
  'avocados': 'Fresh Produce',

  // Fresh Herbs
  'basil': 'Fresh Produce',
  'fresh basil': 'Fresh Produce',
  'basil leaves': 'Fresh Produce',
  'mint': 'Fresh Produce',
  'fresh mint': 'Fresh Produce',
  'mint leaves': 'Fresh Produce',
  'coriander': 'Fresh Produce',
  'fresh coriander': 'Fresh Produce',
  'cilantro': 'Fresh Produce',
  'parsley': 'Fresh Produce',
  'fresh parsley': 'Fresh Produce',
  'flat leaf parsley': 'Fresh Produce',
  'curly parsley': 'Fresh Produce',
  'dill': 'Fresh Produce',
  'fresh dill': 'Fresh Produce',
  'chive': 'Fresh Produce',
  'chives': 'Fresh Produce',
  'fresh chives': 'Fresh Produce',
  'thyme': 'Fresh Produce',
  'fresh thyme': 'Fresh Produce',
  'rosemary': 'Fresh Produce',
  'fresh rosemary': 'Fresh Produce',
  'sage': 'Fresh Produce',
  'fresh sage': 'Fresh Produce',
  'oregano': 'Fresh Produce',
  'fresh oregano': 'Fresh Produce',
  'tarragon': 'Fresh Produce',
  'fresh tarragon': 'Fresh Produce',
  'bay leaf': 'Fresh Produce',
  'bay leaves': 'Fresh Produce',
  'fresh bay leaves': 'Fresh Produce',
  'lemongrass': 'Fresh Produce',
  'kaffir lime leaves': 'Fresh Produce',

  // Fruits
  'apple': 'Fresh Produce',
  'apples': 'Fresh Produce',
  'apple sliced': 'Fresh Produce',
  'banana': 'Fresh Produce',
  'bananas': 'Fresh Produce',
  'ripe banana': 'Fresh Produce',
  'orange': 'Fresh Produce',
  'oranges': 'Fresh Produce',
  'lemon': 'Fresh Produce',
  'lemons': 'Fresh Produce',
  'lemon zest': 'Fresh Produce',
  'lime': 'Fresh Produce',
  'limes': 'Fresh Produce',
  'lime zest': 'Fresh Produce',
  'grapefruit': 'Fresh Produce',
  'clementine': 'Fresh Produce',
  'clementines': 'Fresh Produce',
  'satsuma': 'Fresh Produce',
  'satsumas': 'Fresh Produce',
  'tangerine': 'Fresh Produce',
  'mandarin': 'Fresh Produce',
  'pear': 'Fresh Produce',
  'pears': 'Fresh Produce',
  'plum': 'Fresh Produce',
  'plums': 'Fresh Produce',
  'peach': 'Fresh Produce',
  'peaches': 'Fresh Produce',
  'nectarine': 'Fresh Produce',
  'nectarines': 'Fresh Produce',
  'apricot': 'Fresh Produce',
  'apricots': 'Fresh Produce',
  'cherry': 'Fresh Produce',
  'cherries': 'Fresh Produce',
  'grape': 'Fresh Produce',
  'grapes': 'Fresh Produce',
  'strawberry': 'Fresh Produce',
  'strawberries': 'Fresh Produce',
  'raspberry': 'Fresh Produce',
  'raspberries': 'Fresh Produce',
  'blackberry': 'Fresh Produce',
  'blackberries': 'Fresh Produce',
  'blueberry': 'Fresh Produce',
  'blueberries': 'Fresh Produce',
  'cranberry': 'Fresh Produce',
  'cranberries': 'Fresh Produce',
  'mango': 'Fresh Produce',
  'mangoes': 'Fresh Produce',
  'pineapple': 'Fresh Produce',
  'melon': 'Fresh Produce',
  'watermelon': 'Fresh Produce',
  'cantaloupe': 'Fresh Produce',
  'honeydew': 'Fresh Produce',
  'kiwi': 'Fresh Produce',
  'kiwi fruit': 'Fresh Produce',
  'papaya': 'Fresh Produce',
  'passion fruit': 'Fresh Produce',
  'pomegranate': 'Fresh Produce',
  'fig': 'Fresh Produce',
  'figs': 'Fresh Produce',
  'date': 'Fresh Produce',
  'dates': 'Fresh Produce',
  'fresh dates': 'Fresh Produce',
  'rhubarb': 'Fresh Produce',
  'coconut': 'Fresh Produce',
  'fresh coconut': 'Fresh Produce',

  // ===== MEAT & FISH =====
  // Chicken
  'chicken': 'Meat & Fish',
  'chicken breast': 'Meat & Fish',
  'chicken breasts': 'Meat & Fish',
  'skinless chicken breast': 'Meat & Fish',
  'skinless chicken breasts': 'Meat & Fish',
  'boneless chicken breast': 'Meat & Fish',
  'boneless skinless chicken breast': 'Meat & Fish',
  'boneless skinless chicken breasts': 'Meat & Fish',
  'chicken thigh': 'Meat & Fish',
  'chicken thighs': 'Meat & Fish',
  'boneless chicken thigh': 'Meat & Fish',
  'boneless chicken thighs': 'Meat & Fish',
  'skinless chicken thigh': 'Meat & Fish',
  'skinless chicken thighs': 'Meat & Fish',
  'boneless skinless chicken thigh': 'Meat & Fish',
  'boneless skinless chicken thighs': 'Meat & Fish',
  'diced chicken': 'Meat & Fish',
  'diced chicken thigh': 'Meat & Fish',
  'diced chicken breast': 'Meat & Fish',
  'chicken drumstick': 'Meat & Fish',
  'chicken drumsticks': 'Meat & Fish',
  'chicken wing': 'Meat & Fish',
  'chicken wings': 'Meat & Fish',
  'chicken leg': 'Meat & Fish',
  'chicken legs': 'Meat & Fish',
  'whole chicken': 'Meat & Fish',
  'roasting chicken': 'Meat & Fish',
  'chicken mince': 'Meat & Fish',
  'minced chicken': 'Meat & Fish',
  'ground chicken': 'Meat & Fish',
  'chicken fillet': 'Meat & Fish',
  'chicken fillets': 'Meat & Fish',

  // Beef
  'beef': 'Meat & Fish',
  'beef mince': 'Meat & Fish',
  'minced beef': 'Meat & Fish',
  'ground beef': 'Meat & Fish',
  'lean minced beef': 'Meat & Fish',
  'lean mince': 'Meat & Fish',
  'beef steak': 'Meat & Fish',
  'steak': 'Meat & Fish',
  'sirloin': 'Meat & Fish',
  'sirloin steak': 'Meat & Fish',
  'ribeye': 'Meat & Fish',
  'ribeye steak': 'Meat & Fish',
  'fillet steak': 'Meat & Fish',
  'rump steak': 'Meat & Fish',
  'braising steak': 'Meat & Fish',
  'stewing beef': 'Meat & Fish',
  'beef brisket': 'Meat & Fish',
  'beef joint': 'Meat & Fish',
  'roasting beef': 'Meat & Fish',
  'beef shin': 'Meat & Fish',
  'beef cheek': 'Meat & Fish',
  'oxtail': 'Meat & Fish',
  'diced beef': 'Meat & Fish',

  // Pork
  'pork': 'Meat & Fish',
  'pork chop': 'Meat & Fish',
  'pork chops': 'Meat & Fish',
  'pork loin': 'Meat & Fish',
  'pork tenderloin': 'Meat & Fish',
  'pork fillet': 'Meat & Fish',
  'pork belly': 'Meat & Fish',
  'pork shoulder': 'Meat & Fish',
  'pork mince': 'Meat & Fish',
  'minced pork': 'Meat & Fish',
  'ground pork': 'Meat & Fish',
  'diced pork': 'Meat & Fish',
  'pork ribs': 'Meat & Fish',
  'spare ribs': 'Meat & Fish',
  'bacon': 'Meat & Fish',
  'streaky bacon': 'Meat & Fish',
  'back bacon': 'Meat & Fish',
  'smoked bacon': 'Meat & Fish',
  'unsmoked bacon': 'Meat & Fish',
  'bacon rashers': 'Meat & Fish',
  'bacon lardons': 'Meat & Fish',
  'lardons': 'Meat & Fish',
  'pancetta': 'Meat & Fish',
  'gammon': 'Meat & Fish',
  'gammon steak': 'Meat & Fish',
  'ham hock': 'Meat & Fish',

  // Lamb
  'lamb': 'Meat & Fish',
  'lamb chop': 'Meat & Fish',
  'lamb chops': 'Meat & Fish',
  'lamb leg': 'Meat & Fish',
  'leg of lamb': 'Meat & Fish',
  'lamb shoulder': 'Meat & Fish',
  'lamb mince': 'Meat & Fish',
  'minced lamb': 'Meat & Fish',
  'ground lamb': 'Meat & Fish',
  'diced lamb': 'Meat & Fish',
  'lamb shank': 'Meat & Fish',
  'lamb shanks': 'Meat & Fish',
  'lamb neck': 'Meat & Fish',
  'rack of lamb': 'Meat & Fish',
  'lamb fillet': 'Meat & Fish',

  // Sausages
  'sausage': 'Meat & Fish',
  'sausages': 'Meat & Fish',
  'pork sausage': 'Meat & Fish',
  'pork sausages': 'Meat & Fish',
  'cumberland sausage': 'Meat & Fish',
  'cumberland sausages': 'Meat & Fish',
  'lincolnshire sausage': 'Meat & Fish',
  'lincolnshire sausages': 'Meat & Fish',
  'chipolata': 'Meat & Fish',
  'chipolatas': 'Meat & Fish',
  'chorizo': 'Meat & Fish',
  'cooking chorizo': 'Meat & Fish',

  // Other meat
  'turkey': 'Meat & Fish',
  'turkey breast': 'Meat & Fish',
  'turkey mince': 'Meat & Fish',
  'minced turkey': 'Meat & Fish',
  'duck': 'Meat & Fish',
  'duck breast': 'Meat & Fish',
  'duck leg': 'Meat & Fish',
  'venison': 'Meat & Fish',
  'rabbit': 'Meat & Fish',
  'liver': 'Meat & Fish',
  'chicken liver': 'Meat & Fish',
  'lambs liver': 'Meat & Fish',
  'kidney': 'Meat & Fish',

  // Fish
  'fish': 'Meat & Fish',
  'salmon': 'Meat & Fish',
  'salmon fillet': 'Meat & Fish',
  'salmon fillets': 'Meat & Fish',
  'smoked salmon': 'Meat & Fish',
  'cod': 'Meat & Fish',
  'cod fillet': 'Meat & Fish',
  'cod fillets': 'Meat & Fish',
  'haddock': 'Meat & Fish',
  'smoked haddock': 'Meat & Fish',
  'sea bass': 'Meat & Fish',
  'sea bream': 'Meat & Fish',
  'trout': 'Meat & Fish',
  'mackerel': 'Meat & Fish',
  'smoked mackerel': 'Meat & Fish',
  'tuna': 'Meat & Fish',
  'tuna steak': 'Meat & Fish',
  'fresh tuna': 'Meat & Fish',
  'plaice': 'Meat & Fish',
  'sole': 'Meat & Fish',
  'dover sole': 'Meat & Fish',
  'lemon sole': 'Meat & Fish',
  'halibut': 'Meat & Fish',
  'monkfish': 'Meat & Fish',
  'swordfish': 'Meat & Fish',
  'sardine': 'Meat & Fish',
  'sardines': 'Meat & Fish',
  'fresh sardines': 'Meat & Fish',
  'anchovy': 'Meat & Fish',
  'anchovies': 'Meat & Fish',
  'fresh anchovies': 'Meat & Fish',
  'white fish': 'Meat & Fish',
  'white fish fillet': 'Meat & Fish',

  // Seafood
  'prawn': 'Meat & Fish',
  'prawns': 'Meat & Fish',
  'king prawn': 'Meat & Fish',
  'king prawns': 'Meat & Fish',
  'tiger prawn': 'Meat & Fish',
  'tiger prawns': 'Meat & Fish',
  'shrimp': 'Meat & Fish',
  'scallop': 'Meat & Fish',
  'scallops': 'Meat & Fish',
  'mussel': 'Meat & Fish',
  'mussels': 'Meat & Fish',
  'clam': 'Meat & Fish',
  'clams': 'Meat & Fish',
  'oyster': 'Meat & Fish',
  'oysters': 'Meat & Fish',
  'squid': 'Meat & Fish',
  'calamari': 'Meat & Fish',
  'octopus': 'Meat & Fish',
  'crab': 'Meat & Fish',
  'crab meat': 'Meat & Fish',
  'lobster': 'Meat & Fish',
  'crayfish': 'Meat & Fish',
  'seafood mix': 'Meat & Fish',
  'mixed seafood': 'Meat & Fish',

  // ===== DAIRY & EGGS =====
  // Milk
  'milk': 'Dairy & Eggs',
  'whole milk': 'Dairy & Eggs',
  'semi skimmed milk': 'Dairy & Eggs',
  'semi-skimmed milk': 'Dairy & Eggs',
  'skimmed milk': 'Dairy & Eggs',
  'full fat milk': 'Dairy & Eggs',
  'milk 2%': 'Dairy & Eggs',
  'oat milk': 'Dairy & Eggs',
  'almond milk': 'Dairy & Eggs',
  'soya milk': 'Dairy & Eggs',
  'soy milk': 'Dairy & Eggs',
  'coconut milk drink': 'Dairy & Eggs',
  'buttermilk': 'Dairy & Eggs',

  // Cream
  'cream': 'Dairy & Eggs',
  'single cream': 'Dairy & Eggs',
  'double cream': 'Dairy & Eggs',
  'whipping cream': 'Dairy & Eggs',
  'heavy cream': 'Dairy & Eggs',
  'clotted cream': 'Dairy & Eggs',
  'soured cream': 'Dairy & Eggs',
  'sour cream': 'Dairy & Eggs',
  'creme fraiche': 'Dairy & Eggs',
  'crème fraîche': 'Dairy & Eggs',
  'half and half': 'Dairy & Eggs',

  // Cheese
  'cheese': 'Dairy & Eggs',
  'cheddar': 'Dairy & Eggs',
  'cheddar cheese': 'Dairy & Eggs',
  'mature cheddar': 'Dairy & Eggs',
  'mild cheddar': 'Dairy & Eggs',
  'extra mature cheddar': 'Dairy & Eggs',
  'red leicester': 'Dairy & Eggs',
  'double gloucester': 'Dairy & Eggs',
  'stilton': 'Dairy & Eggs',
  'blue cheese': 'Dairy & Eggs',
  'brie': 'Dairy & Eggs',
  'camembert': 'Dairy & Eggs',
  'mozzarella': 'Dairy & Eggs',
  'fresh mozzarella': 'Dairy & Eggs',
  'low fat mozzarella': 'Dairy & Eggs',
  'parmesan': 'Dairy & Eggs',
  'parmigiano reggiano': 'Dairy & Eggs',
  'grated parmesan': 'Dairy & Eggs',
  'freshly grated parmesan': 'Dairy & Eggs',
  'pecorino': 'Dairy & Eggs',
  'gruyere': 'Dairy & Eggs',
  'emmental': 'Dairy & Eggs',
  'gouda': 'Dairy & Eggs',
  'edam': 'Dairy & Eggs',
  'feta': 'Dairy & Eggs',
  'feta cheese': 'Dairy & Eggs',
  'halloumi': 'Dairy & Eggs',
  'goat cheese': 'Dairy & Eggs',
  'goats cheese': 'Dairy & Eggs',
  'cream cheese': 'Dairy & Eggs',
  'philadelphia': 'Dairy & Eggs',
  'mascarpone': 'Dairy & Eggs',
  'ricotta': 'Dairy & Eggs',
  'whole milk ricotta': 'Dairy & Eggs',
  'cottage cheese': 'Dairy & Eggs',
  'cottage cheese reduced fat': 'Dairy & Eggs',
  'paneer': 'Dairy & Eggs',
  'quark': 'Dairy & Eggs',
  'cheese slices': 'Dairy & Eggs',
  'grated cheese': 'Dairy & Eggs',

  // Yoghurt
  'yoghurt': 'Dairy & Eggs',
  'yogurt': 'Dairy & Eggs',
  'natural yoghurt': 'Dairy & Eggs',
  'natural yogurt': 'Dairy & Eggs',
  'greek yoghurt': 'Dairy & Eggs',
  'greek yogurt': 'Dairy & Eggs',
  'greek yogurt 0%': 'Dairy & Eggs',
  'fat free yoghurt': 'Dairy & Eggs',
  'low fat yoghurt': 'Dairy & Eggs',
  'full fat yoghurt': 'Dairy & Eggs',
  'flavoured yoghurt': 'Dairy & Eggs',

  // Butter
  'butter': 'Dairy & Eggs',
  'unsalted butter': 'Dairy & Eggs',
  'salted butter': 'Dairy & Eggs',
  'spreadable butter': 'Dairy & Eggs',
  'margarine': 'Dairy & Eggs',
  'spread': 'Dairy & Eggs',

  // Eggs
  'egg': 'Dairy & Eggs',
  'eggs': 'Dairy & Eggs',
  'large egg': 'Dairy & Eggs',
  'large eggs': 'Dairy & Eggs',
  'medium egg': 'Dairy & Eggs',
  'medium eggs': 'Dairy & Eggs',
  'free range egg': 'Dairy & Eggs',
  'free range eggs': 'Dairy & Eggs',
  'organic eggs': 'Dairy & Eggs',
  'egg white': 'Dairy & Eggs',
  'egg whites': 'Dairy & Eggs',
  'egg yolk': 'Dairy & Eggs',
  'egg yolks': 'Dairy & Eggs',
  'quail egg': 'Dairy & Eggs',
  'quail eggs': 'Dairy & Eggs',
  'duck egg': 'Dairy & Eggs',
  'duck eggs': 'Dairy & Eggs',

  // ===== BAKERY =====
  'bread': 'Bakery',
  'white bread': 'Bakery',
  'brown bread': 'Bakery',
  'wholemeal bread': 'Bakery',
  'granary bread': 'Bakery',
  'sourdough': 'Bakery',
  'sourdough bread': 'Bakery',
  'sliced bread': 'Bakery',
  'bread loaf': 'Bakery',
  'baguette': 'Bakery',
  'french bread': 'Bakery',
  'ciabatta': 'Bakery',
  'focaccia': 'Bakery',
  'roll': 'Bakery',
  'rolls': 'Bakery',
  'bread roll': 'Bakery',
  'bread rolls': 'Bakery',
  'burger bun': 'Bakery',
  'burger buns': 'Bakery',
  'brioche': 'Bakery',
  'brioche bun': 'Bakery',
  'brioche buns': 'Bakery',
  'hot dog bun': 'Bakery',
  'hot dog buns': 'Bakery',
  'bagel': 'Bakery',
  'bagels': 'Bakery',
  'english muffin': 'Bakery',
  'english muffins': 'Bakery',
  'crumpet': 'Bakery',
  'crumpets': 'Bakery',
  'croissant': 'Bakery',
  'croissants': 'Bakery',
  'pain au chocolat': 'Bakery',
  'danish pastry': 'Bakery',
  'pastry': 'Bakery',
  'puff pastry': 'Bakery',
  'shortcrust pastry': 'Bakery',
  'filo pastry': 'Bakery',
  'pitta': 'Bakery',
  'pitta bread': 'Bakery',
  'pita': 'Bakery',
  'pita bread': 'Bakery',
  'flatbread': 'Bakery',
  'naan': 'Bakery',
  'naan bread': 'Bakery',
  'plain naan': 'Bakery',
  'garlic naan': 'Bakery',
  'chapati': 'Bakery',
  'chapatis': 'Bakery',
  'roti': 'Bakery',
  'tortilla': 'Bakery',
  'tortillas': 'Bakery',
  'flour tortilla': 'Bakery',
  'flour tortillas': 'Bakery',
  'corn tortilla': 'Bakery',
  'corn tortillas': 'Bakery',
  'wrap': 'Bakery',
  'wraps': 'Bakery',
  'tortilla wrap': 'Bakery',
  'tortilla wraps': 'Bakery',
  'taco shell': 'Bakery',
  'taco shells': 'Bakery',
  'breadcrumb': 'Bakery',
  'breadcrumbs': 'Bakery',
  'panko': 'Bakery',
  'panko breadcrumbs': 'Bakery',
  'crouton': 'Bakery',
  'croutons': 'Bakery',
  'cake': 'Bakery',
  'muffin': 'Bakery',
  'muffins': 'Bakery',
  'scone': 'Bakery',
  'scones': 'Bakery',
  'teacake': 'Bakery',
  'teacakes': 'Bakery',
  'hot cross bun': 'Bakery',
  'hot cross buns': 'Bakery',
  'doughnut': 'Bakery',
  'doughnuts': 'Bakery',
  'donut': 'Bakery',
  'donuts': 'Bakery',

  // ===== CHILLED & DELI =====
  'ham': 'Chilled & Deli',
  'sliced ham': 'Chilled & Deli',
  'cooked ham': 'Chilled & Deli',
  'parma ham': 'Chilled & Deli',
  'prosciutto': 'Chilled & Deli',
  'serrano ham': 'Chilled & Deli',
  'salami': 'Chilled & Deli',
  'chorizo slices': 'Chilled & Deli',
  'sliced chorizo': 'Chilled & Deli',
  'pepperoni': 'Chilled & Deli',
  'pastrami': 'Chilled & Deli',
  'bresaola': 'Chilled & Deli',
  'cooked chicken': 'Chilled & Deli',
  'rotisserie chicken': 'Chilled & Deli',
  'cooked turkey': 'Chilled & Deli',
  'turkey slices': 'Chilled & Deli',
  'pate': 'Chilled & Deli',
  'chicken pate': 'Chilled & Deli',
  'hummus': 'Chilled & Deli',
  'houmous': 'Chilled & Deli',
  'guacamole': 'Chilled & Deli',
  'salsa': 'Chilled & Deli',
  'fresh salsa': 'Chilled & Deli',
  'pico de gallo': 'Chilled & Deli',
  'tzatziki': 'Chilled & Deli',
  'taramasalata': 'Chilled & Deli',
  'dip': 'Chilled & Deli',
  'sour cream dip': 'Chilled & Deli',
  'coleslaw': 'Chilled & Deli',
  'potato salad': 'Chilled & Deli',
  'fresh pasta': 'Chilled & Deli',
  'fresh ravioli': 'Chilled & Deli',
  'fresh tortellini': 'Chilled & Deli',
  'fresh gnocchi': 'Chilled & Deli',
  'gnocchi': 'Chilled & Deli',
  'pesto': 'Chilled & Deli',
  'fresh pesto': 'Chilled & Deli',
  'green pesto': 'Chilled & Deli',
  'red pesto': 'Chilled & Deli',
  'fresh soup': 'Chilled & Deli',
  'soup carton': 'Chilled & Deli',
  'quiche': 'Chilled & Deli',
  'scotch egg': 'Chilled & Deli',
  'scotch eggs': 'Chilled & Deli',
  'pork pie': 'Chilled & Deli',
  'sausage roll': 'Chilled & Deli',
  'sausage rolls': 'Chilled & Deli',
  'samosa': 'Chilled & Deli',
  'samosas': 'Chilled & Deli',
  'spring roll': 'Chilled & Deli',
  'spring rolls': 'Chilled & Deli',
  'ready meal': 'Chilled & Deli',
  'sandwich': 'Chilled & Deli',
  'sandwiches': 'Chilled & Deli',
  'wrap meal': 'Chilled & Deli',
  'salad pot': 'Chilled & Deli',
  'prepared salad': 'Chilled & Deli',
  'stir fry vegetables': 'Chilled & Deli',
  'stir fry mix': 'Chilled & Deli',
  'tofu': 'Chilled & Deli',
  'tempeh': 'Chilled & Deli',
  'olives': 'Chilled & Deli',
  'stuffed olives': 'Chilled & Deli',
  'antipasti': 'Chilled & Deli',
  'sun dried tomatoes': 'Chilled & Deli',
  'sundried tomatoes': 'Chilled & Deli',
  'sun-dried tomatoes': 'Chilled & Deli',
  'sliced sun-dried tomatoes': 'Chilled & Deli',
  'pickled vegetables': 'Chilled & Deli',
  'kimchi': 'Chilled & Deli',
  'sauerkraut': 'Chilled & Deli',

  // ===== FROZEN =====
  'frozen peas': 'Frozen',
  'frozen sweetcorn': 'Frozen',
  'frozen spinach': 'Frozen',
  'frozen broccoli': 'Frozen',
  'frozen mixed vegetables': 'Frozen',
  'frozen vegetables': 'Frozen',
  'frozen chips': 'Frozen',
  'oven chips': 'Frozen',
  'frozen roast potatoes': 'Frozen',
  'frozen berries': 'Frozen',
  'frozen fruit': 'Frozen',
  'frozen raspberries': 'Frozen',
  'frozen strawberries': 'Frozen',
  'frozen blueberries': 'Frozen',
  'frozen mango': 'Frozen',
  'ice cream': 'Frozen',
  'frozen yogurt': 'Frozen',
  'sorbet': 'Frozen',
  'frozen pizza': 'Frozen',
  'frozen pie': 'Frozen',
  'frozen pastry': 'Frozen',
  'frozen puff pastry': 'Frozen',
  'frozen filo': 'Frozen',
  'fish fingers': 'Frozen',
  'fish cakes': 'Frozen',
  'frozen fish': 'Frozen',
  'frozen prawns': 'Frozen',
  'frozen seafood': 'Frozen',
  'chicken nuggets': 'Frozen',
  'frozen chicken': 'Frozen',
  'frozen burgers': 'Frozen',
  'frozen sausages': 'Frozen',
  'frozen ready meal': 'Frozen',
  'frozen dessert': 'Frozen',
  'frozen cheesecake': 'Frozen',
  'frozen gateau': 'Frozen',
  'frozen yorkshire puddings': 'Frozen',
  'yorkshire puddings': 'Frozen',
  'frozen garlic bread': 'Frozen',
  'frozen naan': 'Frozen',
  'frozen dumplings': 'Frozen',
  'frozen gyoza': 'Frozen',
  'frozen spring rolls': 'Frozen',
  'frozen samosas': 'Frozen',
  'frozen edamame': 'Frozen',
  'edamame': 'Frozen',

  // ===== CUPBOARD STAPLES =====
  // Pasta & Noodles
  'pasta': 'Cupboard Staples',
  'spaghetti': 'Cupboard Staples',
  'penne': 'Cupboard Staples',
  'fusilli': 'Cupboard Staples',
  'rigatoni': 'Cupboard Staples',
  'tagliatelle': 'Cupboard Staples',
  'fettuccine': 'Cupboard Staples',
  'linguine': 'Cupboard Staples',
  'farfalle': 'Cupboard Staples',
  'orzo': 'Cupboard Staples',
  'macaroni': 'Cupboard Staples',
  'lasagne sheets': 'Cupboard Staples',
  'lasagna sheets': 'Cupboard Staples',
  'cannelloni': 'Cupboard Staples',
  'egg noodles': 'Cupboard Staples',
  'dried egg noodles': 'Cupboard Staples',
  'medium egg noodles': 'Cupboard Staples',
  'dried wheat noodles': 'Cupboard Staples',
  'rice noodles': 'Cupboard Staples',
  'noodles': 'Cupboard Staples',
  'ramen': 'Cupboard Staples',
  'ramen noodles': 'Cupboard Staples',
  'udon': 'Cupboard Staples',
  'udon noodles': 'Cupboard Staples',
  'soba': 'Cupboard Staples',
  'soba noodles': 'Cupboard Staples',
  'vermicelli': 'Cupboard Staples',
  'rice vermicelli': 'Cupboard Staples',
  'short pasta': 'Cupboard Staples',
  'short ribbed pasta': 'Cupboard Staples',
  'gemelli': 'Cupboard Staples',

  // Rice & Grains
  'rice': 'Cupboard Staples',
  'white rice': 'Cupboard Staples',
  'basmati rice': 'Cupboard Staples',
  'basmati': 'Cupboard Staples',
  'jasmine rice': 'Cupboard Staples',
  'long grain rice': 'Cupboard Staples',
  'short grain rice': 'Cupboard Staples',
  'short grain white rice': 'Cupboard Staples',
  'brown rice': 'Cupboard Staples',
  'wild rice': 'Cupboard Staples',
  'risotto rice': 'Cupboard Staples',
  'arborio rice': 'Cupboard Staples',
  'sushi rice': 'Cupboard Staples',
  'pilau rice': 'Cupboard Staples',
  'boiled rice': 'Cupboard Staples',
  'plain boiled rice': 'Cupboard Staples',
  'plain boiled long grain rice': 'Cupboard Staples',
  'microwave rice': 'Cupboard Staples',
  'quinoa': 'Cupboard Staples',
  'couscous': 'Cupboard Staples',
  'bulgur wheat': 'Cupboard Staples',
  'bulgur': 'Cupboard Staples',
  'pearl barley': 'Cupboard Staples',
  'barley': 'Cupboard Staples',
  'freekeh': 'Cupboard Staples',
  'farro': 'Cupboard Staples',
  'polenta': 'Cupboard Staples',

  // Tinned goods
  'tinned tomatoes': 'Cupboard Staples',
  'chopped tomatoes': 'Cupboard Staples',
  'canned tomatoes': 'Cupboard Staples',
  'tinned plum tomatoes': 'Cupboard Staples',
  'whole plum tomatoes': 'Cupboard Staples',
  'canned plum tomatoes': 'Cupboard Staples',
  'passata': 'Cupboard Staples',
  'tomato passata': 'Cupboard Staples',
  'tinned tuna': 'Cupboard Staples',
  'canned tuna': 'Cupboard Staples',
  'tuna chunks': 'Cupboard Staples',
  'tinned salmon': 'Cupboard Staples',
  'canned salmon': 'Cupboard Staples',
  'tinned sardines': 'Cupboard Staples',
  'tinned mackerel': 'Cupboard Staples',
  'tinned anchovies': 'Cupboard Staples',
  'anchovies in oil': 'Cupboard Staples',
  'baked beans': 'Cupboard Staples',
  'beans': 'Cupboard Staples',
  'kidney beans': 'Cupboard Staples',
  'red kidney beans': 'Cupboard Staples',
  'cannellini beans': 'Cupboard Staples',
  'butter beans': 'Cupboard Staples',
  'haricot beans': 'Cupboard Staples',
  'black beans': 'Cupboard Staples',
  'borlotti beans': 'Cupboard Staples',
  'mixed beans': 'Cupboard Staples',
  'chickpeas': 'Cupboard Staples',
  'chickpea': 'Cupboard Staples',
  'tinned chickpeas': 'Cupboard Staples',
  'lentils': 'Cupboard Staples',
  'red lentils': 'Cupboard Staples',
  'green lentils': 'Cupboard Staples',
  'puy lentils': 'Cupboard Staples',
  'brown lentils': 'Cupboard Staples',
  'tinned sweetcorn': 'Cupboard Staples',
  'canned sweetcorn': 'Cupboard Staples',
  'sweetcorn kernels': 'Cupboard Staples',
  'coconut milk': 'Cupboard Staples',
  'tinned coconut milk': 'Cupboard Staples',
  'full fat coconut milk': 'Cupboard Staples',
  'light coconut milk': 'Cupboard Staples',
  'coconut cream': 'Cupboard Staples',
  'creamed coconut': 'Cupboard Staples',
  'solid creamed coconut': 'Cupboard Staples',

  // Stock & Broth
  'stock': 'Cupboard Staples',
  'chicken stock': 'Cupboard Staples',
  'beef stock': 'Cupboard Staples',
  'vegetable stock': 'Cupboard Staples',
  'fish stock': 'Cupboard Staples',
  'stock cube': 'Cupboard Staples',
  'stock cubes': 'Cupboard Staples',
  'chicken stock cube': 'Cupboard Staples',
  'chicken stock cubes': 'Cupboard Staples',
  'beef stock cube': 'Cupboard Staples',
  'beef stock cubes': 'Cupboard Staples',
  'vegetable stock cube': 'Cupboard Staples',
  'vegetable stock cubes': 'Cupboard Staples',
  'stock pot': 'Cupboard Staples',
  'stock pots': 'Cupboard Staples',
  'bouillon': 'Cupboard Staples',
  'broth': 'Cupboard Staples',
  'chicken broth': 'Cupboard Staples',
  'beef broth': 'Cupboard Staples',
  'low sodium chicken broth': 'Cupboard Staples',
  'low-sodium chicken broth': 'Cupboard Staples',
  'low sodium chicken stock': 'Cupboard Staples',
  'low-sodium chicken stock': 'Cupboard Staples',
  'chicken stock mix': 'Cupboard Staples',
  'chicken stock mix intense': 'Cupboard Staples',

  // Sauces & Condiments
  'soy sauce': 'Cupboard Staples',
  'light soy sauce': 'Cupboard Staples',
  'dark soy sauce': 'Cupboard Staples',
  'tamari': 'Cupboard Staples',
  'fish sauce': 'Cupboard Staples',
  'oyster sauce': 'Cupboard Staples',
  'hoisin sauce': 'Cupboard Staples',
  'teriyaki sauce': 'Cupboard Staples',
  'sweet chilli sauce': 'Cupboard Staples',
  'sriracha': 'Cupboard Staples',
  'hot sauce': 'Cupboard Staples',
  'tabasco': 'Cupboard Staples',
  'vinegar hot sauce': 'Cupboard Staples',
  'vinegar-based hot sauce': 'Cupboard Staples',
  'worcestershire sauce': 'Cupboard Staples',
  'tomato ketchup': 'Cupboard Staples',
  'ketchup': 'Cupboard Staples',
  'brown sauce': 'Cupboard Staples',
  'hp sauce': 'Cupboard Staples',
  'bbq sauce': 'Cupboard Staples',
  'barbecue sauce': 'Cupboard Staples',
  'mayonnaise': 'Cupboard Staples',
  'mayo': 'Cupboard Staples',
  'salad cream': 'Cupboard Staples',
  'mustard': 'Cupboard Staples',
  'english mustard': 'Cupboard Staples',
  'dijon mustard': 'Cupboard Staples',
  'wholegrain mustard': 'Cupboard Staples',
  'french mustard': 'Cupboard Staples',
  'american mustard': 'Cupboard Staples',
  'tomato puree': 'Cupboard Staples',
  'tomato purée': 'Cupboard Staples',
  'tomato paste': 'Cupboard Staples',
  'curry paste': 'Cupboard Staples',
  'tikka paste': 'Cupboard Staples',
  'korma paste': 'Cupboard Staples',
  'thai curry paste': 'Cupboard Staples',
  'red curry paste': 'Cupboard Staples',
  'green curry paste': 'Cupboard Staples',
  'harissa': 'Cupboard Staples',
  'harissa paste': 'Cupboard Staples',
  'miso paste': 'Cupboard Staples',
  'miso': 'Cupboard Staples',
  'tahini': 'Cupboard Staples',
  'peanut butter': 'Cupboard Staples',
  'almond butter': 'Cupboard Staples',
  'cashew butter': 'Cupboard Staples',
  'jam': 'Cupboard Staples',
  'strawberry jam': 'Cupboard Staples',
  'raspberry jam': 'Cupboard Staples',
  'marmalade': 'Cupboard Staples',
  'honey': 'Cupboard Staples',
  'clear honey': 'Cupboard Staples',
  'runny honey': 'Cupboard Staples',
  'set honey': 'Cupboard Staples',
  'maple syrup': 'Cupboard Staples',
  'golden syrup': 'Cupboard Staples',
  'treacle': 'Cupboard Staples',
  'black treacle': 'Cupboard Staples',
  'molasses': 'Cupboard Staples',
  'agave': 'Cupboard Staples',
  'agave syrup': 'Cupboard Staples',
  'salsa verde': 'Cupboard Staples',

  // Vinegars
  'vinegar': 'Cupboard Staples',
  'white wine vinegar': 'Cupboard Staples',
  'red wine vinegar': 'Cupboard Staples',
  'balsamic vinegar': 'Cupboard Staples',
  'balsamic': 'Cupboard Staples',
  'cider vinegar': 'Cupboard Staples',
  'apple cider vinegar': 'Cupboard Staples',
  'malt vinegar': 'Cupboard Staples',
  'rice vinegar': 'Cupboard Staples',
  'rice wine vinegar': 'Cupboard Staples',
  'sherry vinegar': 'Cupboard Staples',

  // ===== BAKING & COOKING INGREDIENTS =====
  // Flour
  'flour': 'Baking & Cooking Ingredients',
  'plain flour': 'Baking & Cooking Ingredients',
  'self raising flour': 'Baking & Cooking Ingredients',
  'self-raising flour': 'Baking & Cooking Ingredients',
  'strong flour': 'Baking & Cooking Ingredients',
  'bread flour': 'Baking & Cooking Ingredients',
  'wholemeal flour': 'Baking & Cooking Ingredients',
  'whole wheat flour': 'Baking & Cooking Ingredients',
  'all purpose flour': 'Baking & Cooking Ingredients',
  'all-purpose flour': 'Baking & Cooking Ingredients',
  'cornflour': 'Baking & Cooking Ingredients',
  'corn flour': 'Baking & Cooking Ingredients',
  'cornstarch': 'Baking & Cooking Ingredients',
  'rice flour': 'Baking & Cooking Ingredients',
  'gram flour': 'Baking & Cooking Ingredients',
  'chickpea flour': 'Baking & Cooking Ingredients',
  'almond flour': 'Baking & Cooking Ingredients',
  'ground almonds': 'Baking & Cooking Ingredients',
  'coconut flour': 'Baking & Cooking Ingredients',
  'semolina': 'Baking & Cooking Ingredients',
  '00 flour': 'Baking & Cooking Ingredients',
  'tipo 00': 'Baking & Cooking Ingredients',

  // Sugar
  'sugar': 'Baking & Cooking Ingredients',
  'white sugar': 'Baking & Cooking Ingredients',
  'caster sugar': 'Baking & Cooking Ingredients',
  'granulated sugar': 'Baking & Cooking Ingredients',
  'brown sugar': 'Baking & Cooking Ingredients',
  'light brown sugar': 'Baking & Cooking Ingredients',
  'dark brown sugar': 'Baking & Cooking Ingredients',
  'soft brown sugar': 'Baking & Cooking Ingredients',
  'muscovado sugar': 'Baking & Cooking Ingredients',
  'demerara sugar': 'Baking & Cooking Ingredients',
  'icing sugar': 'Baking & Cooking Ingredients',
  'powdered sugar': 'Baking & Cooking Ingredients',
  'confectioners sugar': 'Baking & Cooking Ingredients',
  'coconut sugar': 'Baking & Cooking Ingredients',

  // Baking essentials
  'baking powder': 'Baking & Cooking Ingredients',
  'bicarbonate of soda': 'Baking & Cooking Ingredients',
  'baking soda': 'Baking & Cooking Ingredients',
  'yeast': 'Baking & Cooking Ingredients',
  'dried yeast': 'Baking & Cooking Ingredients',
  'instant yeast': 'Baking & Cooking Ingredients',
  'fresh yeast': 'Baking & Cooking Ingredients',
  'cream of tartar': 'Baking & Cooking Ingredients',
  'vanilla': 'Baking & Cooking Ingredients',
  'vanilla extract': 'Baking & Cooking Ingredients',
  'vanilla essence': 'Baking & Cooking Ingredients',
  'vanilla pod': 'Baking & Cooking Ingredients',
  'vanilla bean': 'Baking & Cooking Ingredients',
  'almond extract': 'Baking & Cooking Ingredients',
  'rose water': 'Baking & Cooking Ingredients',
  'orange blossom water': 'Baking & Cooking Ingredients',
  'cocoa': 'Baking & Cooking Ingredients',
  'cocoa powder': 'Baking & Cooking Ingredients',
  'cacao powder': 'Baking & Cooking Ingredients',
  'chocolate chips': 'Baking & Cooking Ingredients',
  'dark chocolate': 'Baking & Cooking Ingredients',
  'milk chocolate': 'Baking & Cooking Ingredients',
  'white chocolate': 'Baking & Cooking Ingredients',
  'cooking chocolate': 'Baking & Cooking Ingredients',
  'baking chocolate': 'Baking & Cooking Ingredients',
  'gelatine': 'Baking & Cooking Ingredients',
  'gelatin': 'Baking & Cooking Ingredients',
  'agar agar': 'Baking & Cooking Ingredients',
  'food colouring': 'Baking & Cooking Ingredients',

  // Oils
  'oil': 'Baking & Cooking Ingredients',
  'olive oil': 'Baking & Cooking Ingredients',
  'extra virgin olive oil': 'Baking & Cooking Ingredients',
  'extra-virgin olive oil': 'Baking & Cooking Ingredients',
  'vegetable oil': 'Baking & Cooking Ingredients',
  'sunflower oil': 'Baking & Cooking Ingredients',
  'rapeseed oil': 'Baking & Cooking Ingredients',
  'canola oil': 'Baking & Cooking Ingredients',
  'groundnut oil': 'Baking & Cooking Ingredients',
  'peanut oil': 'Baking & Cooking Ingredients',
  'coconut oil': 'Baking & Cooking Ingredients',
  'sesame oil': 'Baking & Cooking Ingredients',
  'toasted sesame oil': 'Baking & Cooking Ingredients',
  'avocado oil': 'Baking & Cooking Ingredients',
  'neutral oil': 'Baking & Cooking Ingredients',
  'cooking oil': 'Baking & Cooking Ingredients',
  'vegetable or avocado oil': 'Baking & Cooking Ingredients',
  'spray oil': 'Baking & Cooking Ingredients',
  'cooking spray': 'Baking & Cooking Ingredients',

  // Salt
  'salt': 'Baking & Cooking Ingredients',
  'table salt': 'Baking & Cooking Ingredients',
  'sea salt': 'Baking & Cooking Ingredients',
  'kosher salt': 'Baking & Cooking Ingredients',
  'rock salt': 'Baking & Cooking Ingredients',
  'flaky salt': 'Baking & Cooking Ingredients',
  'maldon salt': 'Baking & Cooking Ingredients',
  'himalayan salt': 'Baking & Cooking Ingredients',
  'pink salt': 'Baking & Cooking Ingredients',

  // Pepper & Spices (note: 'pepper' alone = bell pepper in Fresh Produce)
  'black pepper': 'Baking & Cooking Ingredients',
  'cracked black pepper': 'Baking & Cooking Ingredients',
  'ground black pepper': 'Baking & Cooking Ingredients',
  'white pepper': 'Baking & Cooking Ingredients',
  'ground white pepper': 'Baking & Cooking Ingredients',
  'peppercorns': 'Baking & Cooking Ingredients',
  'black peppercorns': 'Baking & Cooking Ingredients',
  'mixed peppercorns': 'Baking & Cooking Ingredients',
  'pink peppercorns': 'Baking & Cooking Ingredients',
  'szechuan peppercorns': 'Baking & Cooking Ingredients',
  'paprika': 'Baking & Cooking Ingredients',
  'sweet paprika': 'Baking & Cooking Ingredients',
  'smoked paprika': 'Baking & Cooking Ingredients',
  'hot paprika': 'Baking & Cooking Ingredients',
  'cayenne': 'Baking & Cooking Ingredients',
  'cayenne pepper': 'Baking & Cooking Ingredients',
  'ground cayenne': 'Baking & Cooking Ingredients',
  'chilli powder': 'Baking & Cooking Ingredients',
  'chili powder': 'Baking & Cooking Ingredients',
  'hot chilli powder': 'Baking & Cooking Ingredients',
  'chilli flakes': 'Baking & Cooking Ingredients',
  'red pepper flakes': 'Baking & Cooking Ingredients',
  'red-pepper flakes': 'Baking & Cooking Ingredients',
  'crushed red pepper': 'Baking & Cooking Ingredients',
  'cumin': 'Baking & Cooking Ingredients',
  'ground cumin': 'Baking & Cooking Ingredients',
  'cumin seeds': 'Baking & Cooking Ingredients',
  'ground coriander': 'Baking & Cooking Ingredients',
  'coriander powder': 'Baking & Cooking Ingredients',
  'dried coriander': 'Baking & Cooking Ingredients',
  'coriander seeds': 'Baking & Cooking Ingredients',
  'turmeric': 'Baking & Cooking Ingredients',
  'ground turmeric': 'Baking & Cooking Ingredients',
  'turmeric powder': 'Baking & Cooking Ingredients',
  'ground ginger': 'Baking & Cooking Ingredients',
  'ginger spice': 'Baking & Cooking Ingredients',
  'dried ginger': 'Baking & Cooking Ingredients',
  'ginger powder': 'Baking & Cooking Ingredients',
  'ginger paste': 'Baking & Cooking Ingredients',
  'cinnamon': 'Baking & Cooking Ingredients',
  'ground cinnamon': 'Baking & Cooking Ingredients',
  'cinnamon stick': 'Baking & Cooking Ingredients',
  'cinnamon sticks': 'Baking & Cooking Ingredients',
  'nutmeg': 'Baking & Cooking Ingredients',
  'ground nutmeg': 'Baking & Cooking Ingredients',
  'whole nutmeg': 'Baking & Cooking Ingredients',
  'clove': 'Baking & Cooking Ingredients',
  'cloves': 'Baking & Cooking Ingredients',
  'whole cloves': 'Baking & Cooking Ingredients',
  'ground cloves': 'Baking & Cooking Ingredients',
  'cardamom': 'Baking & Cooking Ingredients',
  'cardamom pods': 'Baking & Cooking Ingredients',
  'green cardamom': 'Baking & Cooking Ingredients',
  'ground cardamom': 'Baking & Cooking Ingredients',
  'star anise': 'Baking & Cooking Ingredients',
  'allspice': 'Baking & Cooking Ingredients',
  'ground allspice': 'Baking & Cooking Ingredients',
  'five spice': 'Baking & Cooking Ingredients',
  'chinese five spice': 'Baking & Cooking Ingredients',
  'mixed spice': 'Baking & Cooking Ingredients',
  'garam masala': 'Baking & Cooking Ingredients',
  'curry powder': 'Baking & Cooking Ingredients',
  'madras curry powder': 'Baking & Cooking Ingredients',
  'tikka masala': 'Baking & Cooking Ingredients',
  'tandoori spice': 'Baking & Cooking Ingredients',
  'cajun seasoning': 'Baking & Cooking Ingredients',
  'jerk seasoning': 'Baking & Cooking Ingredients',
  'taco seasoning': 'Baking & Cooking Ingredients',
  'fajita seasoning': 'Baking & Cooking Ingredients',
  'ras el hanout': 'Baking & Cooking Ingredients',
  'za\'atar': 'Baking & Cooking Ingredients',
  'zaatar': 'Baking & Cooking Ingredients',
  'sumac': 'Baking & Cooking Ingredients',
  'saffron': 'Baking & Cooking Ingredients',
  'fennel seeds': 'Baking & Cooking Ingredients',
  'caraway seeds': 'Baking & Cooking Ingredients',
  'mustard seeds': 'Baking & Cooking Ingredients',
  'black mustard seeds': 'Baking & Cooking Ingredients',
  'yellow mustard seeds': 'Baking & Cooking Ingredients',
  'fenugreek': 'Baking & Cooking Ingredients',
  'fenugreek seeds': 'Baking & Cooking Ingredients',
  'nigella seeds': 'Baking & Cooking Ingredients',
  'poppy seeds': 'Baking & Cooking Ingredients',
  'sesame seeds': 'Baking & Cooking Ingredients',
  'white sesame seeds': 'Baking & Cooking Ingredients',
  'toasted sesame seeds': 'Baking & Cooking Ingredients',
  'toasted white sesame seeds': 'Baking & Cooking Ingredients',
  'black sesame seeds': 'Baking & Cooking Ingredients',
  'onion powder': 'Baking & Cooking Ingredients',
  'garlic powder': 'Baking & Cooking Ingredients',
  'garlic granules': 'Baking & Cooking Ingredients',
  'celery salt': 'Baking & Cooking Ingredients',
  'msg': 'Baking & Cooking Ingredients',
  'msg optional': 'Baking & Cooking Ingredients',

  // Dried herbs
  'dried oregano': 'Baking & Cooking Ingredients',
  'dried basil': 'Baking & Cooking Ingredients',
  'dried thyme': 'Baking & Cooking Ingredients',
  'dried rosemary': 'Baking & Cooking Ingredients',
  'dried sage': 'Baking & Cooking Ingredients',
  'dried parsley': 'Baking & Cooking Ingredients',
  'dried dill': 'Baking & Cooking Ingredients',
  'dried tarragon': 'Baking & Cooking Ingredients',
  'dried marjoram': 'Baking & Cooking Ingredients',
  'herbes de provence': 'Baking & Cooking Ingredients',
  'herbs de provence': 'Baking & Cooking Ingredients',
  'italian herbs': 'Baking & Cooking Ingredients',
  'italian seasoning': 'Baking & Cooking Ingredients',
  'mixed herbs': 'Baking & Cooking Ingredients',
  'dried bay leaves': 'Baking & Cooking Ingredients',
  'dried bay leaf': 'Baking & Cooking Ingredients',
  'dried mint': 'Baking & Cooking Ingredients',

  // Seeds & Nuts for cooking
  'chia seeds': 'Baking & Cooking Ingredients',
  'flax': 'Baking & Cooking Ingredients',
  'flax seeds': 'Baking & Cooking Ingredients',
  'flaxseed': 'Baking & Cooking Ingredients',
  'ground flax': 'Baking & Cooking Ingredients',
  'flax ground': 'Baking & Cooking Ingredients',
  'linseed': 'Baking & Cooking Ingredients',
  'sunflower seeds': 'Baking & Cooking Ingredients',
  'pumpkin seeds': 'Baking & Cooking Ingredients',
  'pine nuts': 'Baking & Cooking Ingredients',
  'pine nut': 'Baking & Cooking Ingredients',
  'desiccated coconut': 'Baking & Cooking Ingredients',
  'shredded coconut': 'Baking & Cooking Ingredients',
  'coconut flakes': 'Baking & Cooking Ingredients',

  // Dried fruit for baking
  'sultanas': 'Baking & Cooking Ingredients',
  'raisins': 'Baking & Cooking Ingredients',
  'currants': 'Baking & Cooking Ingredients',
  'dried cranberries': 'Baking & Cooking Ingredients',
  'dried apricots': 'Baking & Cooking Ingredients',
  'dried dates': 'Baking & Cooking Ingredients',
  'medjool dates': 'Baking & Cooking Ingredients',
  'mixed peel': 'Baking & Cooking Ingredients',
  'candied peel': 'Baking & Cooking Ingredients',
  'glace cherries': 'Baking & Cooking Ingredients',

  // Lemon juice (for cooking)
  'lemon juice': 'Baking & Cooking Ingredients',
  'lime juice': 'Baking & Cooking Ingredients',
  'bottled lemon juice': 'Baking & Cooking Ingredients',

  // ===== BREAKFAST =====
  'oats': 'Breakfast',
  'porridge oats': 'Breakfast',
  'rolled oats': 'Breakfast',
  'instant oats': 'Breakfast',
  'steel cut oats': 'Breakfast',
  'oatmeal': 'Breakfast',
  'oats with bran': 'Breakfast',
  'porridge': 'Breakfast',
  'ready brek': 'Breakfast',
  'muesli': 'Breakfast',
  'granola': 'Breakfast',
  'cereal': 'Breakfast',
  'cereals': 'Breakfast',
  'corn flakes': 'Breakfast',
  'cornflakes': 'Breakfast',
  'weetabix': 'Breakfast',
  'shredded wheat': 'Breakfast',
  'shreddies': 'Breakfast',
  'bran flakes': 'Breakfast',
  'all bran': 'Breakfast',
  'special k': 'Breakfast',
  'cheerios': 'Breakfast',
  'rice krispies': 'Breakfast',
  'coco pops': 'Breakfast',
  'frosties': 'Breakfast',
  'crunchy nut': 'Breakfast',
  'alpen': 'Breakfast',
  'fruit and fibre': 'Breakfast',
  'breakfast bar': 'Breakfast',
  'breakfast bars': 'Breakfast',
  'cereal bar': 'Breakfast',
  'cereal bars': 'Breakfast',
  'pancake mix': 'Breakfast',
  'maple syrup or honey': 'Breakfast',

  // ===== DRINKS =====
  'tea': 'Drinks',
  'tea bags': 'Drinks',
  'english breakfast tea': 'Drinks',
  'earl grey': 'Drinks',
  'green tea': 'Drinks',
  'herbal tea': 'Drinks',
  'peppermint tea': 'Drinks',
  'camomile tea': 'Drinks',
  'coffee': 'Drinks',
  'instant coffee': 'Drinks',
  'ground coffee': 'Drinks',
  'coffee beans': 'Drinks',
  'espresso': 'Drinks',
  'decaf coffee': 'Drinks',
  'hot chocolate': 'Drinks',
  'drinking chocolate': 'Drinks',
  'orange juice': 'Drinks',
  'apple juice': 'Drinks',
  'cranberry juice': 'Drinks',
  'grape juice': 'Drinks',
  'pineapple juice': 'Drinks',
  'tomato juice': 'Drinks',
  'fruit juice': 'Drinks',
  'smoothie': 'Drinks',
  'squash': 'Drinks',
  'cordial': 'Drinks',
  'ribena': 'Drinks',
  'robinson\'s': 'Drinks',
  'cola': 'Drinks',
  'coca cola': 'Drinks',
  'pepsi': 'Drinks',
  'lemonade': 'Drinks',
  'fizzy drink': 'Drinks',
  'soft drink': 'Drinks',
  'sparkling water': 'Drinks',
  'still water': 'Drinks',
  'mineral water': 'Drinks',
  'tonic water': 'Drinks',
  'soda water': 'Drinks',
  'energy drink': 'Drinks',
  'sports drink': 'Drinks',
  'water': 'Drinks',
  'boiling water': 'Other',
  'boiled water': 'Other',

  // ===== SNACKS & TREATS =====
  'crisps': 'Snacks & Treats',
  'potato crisps': 'Snacks & Treats',
  'tortilla chips': 'Snacks & Treats',
  'nachos': 'Snacks & Treats',
  'popcorn': 'Snacks & Treats',
  'pretzels': 'Snacks & Treats',
  'rice cakes': 'Snacks & Treats',
  'crackers': 'Snacks & Treats',
  'breadsticks': 'Snacks & Treats',
  'nuts': 'Snacks & Treats',
  'mixed nuts': 'Snacks & Treats',
  'almonds': 'Snacks & Treats',
  'cashews': 'Snacks & Treats',
  'cashew nuts': 'Snacks & Treats',
  'roasted cashews': 'Snacks & Treats',
  'peanuts': 'Snacks & Treats',
  'walnuts': 'Snacks & Treats',
  'pecans': 'Snacks & Treats',
  'pistachios': 'Snacks & Treats',
  'macadamia': 'Snacks & Treats',
  'hazelnuts': 'Snacks & Treats',
  'brazil nuts': 'Snacks & Treats',
  'chocolate': 'Snacks & Treats',
  'chocolate bar': 'Snacks & Treats',
  'cadbury': 'Snacks & Treats',
  'galaxy': 'Snacks & Treats',
  'dairy milk': 'Snacks & Treats',
  'kit kat': 'Snacks & Treats',
  'twix': 'Snacks & Treats',
  'mars bar': 'Snacks & Treats',
  'snickers': 'Snacks & Treats',
  'sweets': 'Snacks & Treats',
  'candy': 'Snacks & Treats',
  'gummy bears': 'Snacks & Treats',
  'haribo': 'Snacks & Treats',
  'biscuits': 'Snacks & Treats',
  'digestives': 'Snacks & Treats',
  'hobnobs': 'Snacks & Treats',
  'rich tea': 'Snacks & Treats',
  'custard creams': 'Snacks & Treats',
  'bourbon creams': 'Snacks & Treats',
  'shortbread': 'Snacks & Treats',
  'cookies': 'Snacks & Treats',
  'chocolate chip cookies': 'Snacks & Treats',
  'jaffa cakes': 'Snacks & Treats',
  'crispy onions': 'Snacks & Treats',
  'dried fruit': 'Snacks & Treats',
  'trail mix': 'Snacks & Treats',
  'fruit snacks': 'Snacks & Treats',

  // ===== HOUSEHOLD =====
  'kitchen roll': 'Household',
  'kitchen paper': 'Household',
  'paper towels': 'Household',
  'toilet roll': 'Household',
  'toilet paper': 'Household',
  'tissues': 'Household',
  'facial tissues': 'Household',
  'cling film': 'Household',
  'plastic wrap': 'Household',
  'foil': 'Household',
  'aluminium foil': 'Household',
  'aluminum foil': 'Household',
  'tin foil': 'Household',
  'baking paper': 'Household',
  'parchment paper': 'Household',
  'greaseproof paper': 'Household',
  'bin bags': 'Household',
  'bin liners': 'Household',
  'refuse sacks': 'Household',
  'sandwich bags': 'Household',
  'freezer bags': 'Household',
  'ziplock bags': 'Household',
  'washing up liquid': 'Household',
  'dish soap': 'Household',
  'dishwasher tablets': 'Household',
  'dishwasher salt': 'Household',
  'rinse aid': 'Household',
  'laundry detergent': 'Household',
  'washing powder': 'Household',
  'fabric softener': 'Household',
  'fabric conditioner': 'Household',
  'bleach': 'Household',
  'surface cleaner': 'Household',
  'all purpose cleaner': 'Household',
  'antibacterial spray': 'Household',
  'kitchen cleaner': 'Household',
  'bathroom cleaner': 'Household',
  'glass cleaner': 'Household',
  'floor cleaner': 'Household',
  'sponge': 'Household',
  'sponges': 'Household',
  'scourer': 'Household',
  'scourers': 'Household',
  'cloths': 'Household',
  'cleaning cloths': 'Household',
  'j cloths': 'Household',
  'rubber gloves': 'Household',
  'marigolds': 'Household',
  'matches': 'Household',
  'candles': 'Household',
  'batteries': 'Household',
  'light bulb': 'Household',
  'light bulbs': 'Household',
}

/**
 * Normalizes an item name for lookup
 * - Lowercase
 * - Trim whitespace
 * - Remove common prefixes/suffixes
 * - Handle plurals
 */
export function normalizeForLookup(itemName: string): string {
  let normalized = itemName.toLowerCase().trim()

  // Remove quantity indicators at the start
  normalized = normalized.replace(/^\d+[\s]*(x\s*)?/i, '')

  // Remove common descriptive prefixes
  const prefixesToRemove = [
    'fresh ', 'frozen ', 'tinned ', 'canned ', 'dried ',
    'organic ', 'free range ', 'free-range ',
    'large ', 'medium ', 'small ', 'mini ',
    'whole ', 'sliced ', 'diced ', 'chopped ', 'minced ', 'grated ', 'shredded ',
    'raw ', 'cooked ', 'roasted ', 'toasted ',
    'boneless ', 'skinless ', 'boneless, skinless ', 'boneless skinless ',
    'lean ', 'extra lean ', 'low fat ', 'low-fat ', 'reduced fat ', 'fat free ', 'fat-free ',
    'unsalted ', 'salted ',
    'plain ', 'natural ',
    'ripe ',
  ]

  for (const prefix of prefixesToRemove) {
    if (normalized.startsWith(prefix)) {
      normalized = normalized.slice(prefix.length)
    }
  }

  // Remove common suffixes
  const suffixesToRemove = [
    ', diced', ', chopped', ', sliced', ', minced', ', grated', ', shredded',
    ', fresh', ', dried', ', frozen', ', canned', ', tinned',
    ', large', ', medium', ', small',
    ', ripe',
    ' (optional)', ' optional',
    ', to taste', ' to taste',
    ', for serving', ' for serving',
    ', for garnish', ' for garnish',
  ]

  for (const suffix of suffixesToRemove) {
    if (normalized.endsWith(suffix)) {
      normalized = normalized.slice(0, -suffix.length)
    }
  }

  // Remove parenthetical content
  normalized = normalized.replace(/\s*\([^)]*\)\s*/g, ' ')

  // Clean up multiple spaces
  normalized = normalized.replace(/\s+/g, ' ').trim()

  return normalized
}

/**
 * Pre-processes an item name for AI categorization
 * More aggressive cleaning for when item isn't in lookup
 */
export function preprocessForAI(itemName: string): string {
  let processed = normalizeForLookup(itemName)

  // Additional cleaning for AI
  // Remove brand names patterns
  processed = processed.replace(/\b(tesco|sainsbury|asda|morrisons|aldi|lidl|waitrose|m&s)\b/gi, '')

  // Remove size/quantity descriptors
  processed = processed.replace(/\b(\d+g|\d+ml|\d+kg|\d+l|\d+ pack|\d+-pack)\b/gi, '')

  // Clean up
  processed = processed.replace(/\s+/g, ' ').trim()

  return processed
}

/**
 * Looks up a category for an item
 * Returns the category name if found, null if not
 */
export function lookupCategory(itemName: string): string | null {
  const normalized = normalizeForLookup(itemName)

  // Direct lookup
  if (CATEGORY_LOOKUP[normalized]) {
    return CATEGORY_LOOKUP[normalized]
  }

  // Try without trailing 's' (simple plural)
  if (normalized.endsWith('s') && normalized.length > 3) {
    const singular = normalized.slice(0, -1)
    if (CATEGORY_LOOKUP[singular]) {
      return CATEGORY_LOOKUP[singular]
    }
  }

  // Try without trailing 'es'
  if (normalized.endsWith('es') && normalized.length > 4) {
    const singular = normalized.slice(0, -2)
    if (CATEGORY_LOOKUP[singular]) {
      return CATEGORY_LOOKUP[singular]
    }
  }

  // Try adding 's' (in case lookup has plural form)
  const plural = normalized + 's'
  if (CATEGORY_LOOKUP[plural]) {
    return CATEGORY_LOOKUP[plural]
  }

  return null
}

/**
 * Keyword-based validation rules for category corrections
 * These catch obvious mismatches the AI might make
 */
export const VALIDATION_KEYWORDS: Record<string, { keywords: string[], notKeywords?: string[] }> = {
  'Meat & Fish': {
    keywords: ['chicken', 'beef', 'pork', 'lamb', 'turkey', 'duck', 'fish', 'salmon', 'cod', 'prawn', 'prawns', 'mince', 'minced', 'steak', 'fillet', 'breast', 'thigh', 'sausage', 'bacon', 'ham'],
    notKeywords: ['stock', 'broth', 'flavour', 'flavoured', 'powder', 'seasoning', 'paste', 'cooked chicken'],
  },
  'Fresh Produce': {
    keywords: ['onion', 'garlic', 'pepper', 'tomato', 'potato', 'carrot', 'celery', 'lettuce', 'spinach', 'broccoli', 'cucumber', 'courgette', 'aubergine', 'mushroom', 'apple', 'banana', 'orange', 'lemon', 'lime', 'berry', 'berries', 'fresh herb', 'fresh mint', 'fresh basil', 'fresh coriander', 'fresh parsley', 'ginger root', 'root ginger'],
    notKeywords: ['frozen', 'tinned', 'canned', 'dried', 'powder', 'ground', 'paste', 'sauce', 'juice', 'puree', 'purée'],
  },
  'Dairy & Eggs': {
    keywords: ['milk', 'cream', 'cheese', 'yoghurt', 'yogurt', 'butter', 'egg', 'eggs', 'parmesan', 'mozzarella', 'cheddar', 'feta', 'ricotta', 'mascarpone', 'crème fraîche', 'creme fraiche', 'sour cream', 'soured cream'],
    notKeywords: ['coconut milk', 'oat milk', 'almond milk', 'soy milk', 'coconut cream'],
  },
  'Cupboard Staples': {
    keywords: ['tinned', 'canned', 'pasta', 'rice', 'noodle', 'stock', 'broth', 'lentil', 'bean', 'chickpea', 'passata', 'chopped tomatoes', 'coconut milk', 'soy sauce', 'sauce', 'honey', 'maple syrup', 'jam', 'peanut butter', 'mustard', 'ketchup', 'mayo', 'mayonnaise', 'vinegar'],
    notKeywords: ['fresh'],
  },
  'Baking & Cooking Ingredients': {
    keywords: ['flour', 'sugar', 'salt', 'pepper', 'oil', 'spice', 'seasoning', 'paprika', 'cumin', 'cinnamon', 'turmeric', 'garam masala', 'curry powder', 'vanilla', 'baking powder', 'bicarbonate', 'yeast', 'cocoa', 'extract', 'dried herb', 'dried oregano', 'dried basil'],
  },
  'Bakery': {
    keywords: ['bread', 'roll', 'bun', 'bagel', 'croissant', 'naan', 'pitta', 'pita', 'tortilla', 'wrap', 'crumpet', 'muffin', 'pastry'],
    notKeywords: ['breadcrumb'],
  },
  'Frozen': {
    keywords: ['frozen', 'ice cream'],
  },
  'Chilled & Deli': {
    keywords: ['hummus', 'houmous', 'guacamole', 'coleslaw', 'pesto', 'fresh pasta', 'gnocchi', 'cooked chicken', 'sliced ham', 'salami', 'prosciutto', 'deli', 'ready meal', 'quiche', 'pate', 'tofu'],
  },
}

/**
 * Validates and potentially corrects a category assignment
 * Returns the corrected category if a mismatch is found
 */
export function validateCategory(itemName: string, suggestedCategory: string): string {
  const lowerItem = itemName.toLowerCase()

  // Check each category's validation rules
  for (const [category, rules] of Object.entries(VALIDATION_KEYWORDS)) {
    // Check if item matches this category's keywords
    const matchesKeyword = rules.keywords.some(kw => lowerItem.includes(kw))
    const matchesNotKeyword = rules.notKeywords?.some(kw => lowerItem.includes(kw)) ?? false

    if (matchesKeyword && !matchesNotKeyword) {
      // Item should be in this category
      if (suggestedCategory !== category) {
        // Suggested category is wrong, correct it
        return category
      }
    }
  }

  // No correction needed
  return suggestedCategory
}
