/**
 * Meal Plan Factory
 * Dynamic meal plan data generation for tests
 *
 * Generated by Test Builder Agent
 * Date: 2025-12-16
 */

import { createRecipe, Recipe } from './recipeFactory'

// Simple generators (no faker dependency)
const generateId = () => `mealplan-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
const randomInt = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min

const daysOfWeek = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const mealTypes = ['breakfast', 'lunch', 'dinner', 'snack'] as const

// ============================================================================
// MEAL PLAN TYPES
// ============================================================================

export type DayOfWeek = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday'
export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack'

export interface PlannedMeal {
  id: string
  mealPlanId: string
  recipeId: string
  recipe?: Recipe
  recipeName: string
  dayOfWeek: DayOfWeek
  mealType: MealType
  servings: number
  notes: string | null
  isLeftover: boolean
  batchCookSourceDay: DayOfWeek | null
  cooked: boolean
  cookedAt: Date | null
  sortOrder: number
  createdAt: Date
  updatedAt: Date
}

export interface MealPlan {
  id: string
  userId: string
  name: string
  weekStarting: Date
  status: 'draft' | 'active' | 'completed' | 'archived'
  meals: PlannedMeal[]
  createdAt: Date
  updatedAt: Date
}

export interface MealPlanSettings {
  macroMode: 'balanced' | 'high_protein' | 'low_carb' | 'custom'
  varietyEnabled: boolean
  dinnerCooldown: number
  lunchCooldown: number
  breakfastCooldown: number
  snackCooldown: number
  minCuisines: number
  maxSameCuisine: number
  shoppingMode: 'minimal' | 'moderate' | 'full'
  expiryPriority: 'high' | 'moderate' | 'low'
  expiryWindow: number
  useItUpItems: string[]
  batchCookingEnabled: boolean
  maxLeftoverDays: number
  priorityOrder: string[]
  feedbackDetail: 'minimal' | 'medium' | 'detailed'
}

// ============================================================================
// PLANNED MEAL FACTORIES
// ============================================================================

/**
 * Creates a single planned meal
 */
export function createPlannedMeal(overrides: Partial<PlannedMeal> = {}): PlannedMeal {
  const now = new Date()
  const recipe = overrides.recipe || createRecipe()

  return {
    id: `meal-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    mealPlanId: overrides.mealPlanId || generateId(),
    recipeId: recipe.id,
    recipe,
    recipeName: recipe.recipeName,
    dayOfWeek: daysOfWeek[randomInt(0, 6)] as DayOfWeek,
    mealType: mealTypes[randomInt(0, 3)],
    servings: randomInt(2, 6),
    notes: null,
    isLeftover: false,
    batchCookSourceDay: null,
    cooked: false,
    cookedAt: null,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
    ...overrides,
  }
}

/**
 * Creates meals for a specific day
 */
export function createDayMeals(
  day: DayOfWeek,
  mealPlanId: string,
  mealTypesToInclude: MealType[] = ['breakfast', 'lunch', 'dinner']
): PlannedMeal[] {
  return mealTypesToInclude.map((mealType, index) =>
    createPlannedMeal({
      mealPlanId,
      dayOfWeek: day,
      mealType,
      sortOrder: index + 1,
    })
  )
}

// ============================================================================
// MEAL PLAN FACTORIES
// ============================================================================

/**
 * Creates a test meal plan with default or custom values
 */
export function createMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  const now = new Date()
  const id = generateId()

  // Default to next Monday
  const weekStarting = getNextMonday()

  return {
    id,
    userId: overrides.userId || `user-${Date.now()}`,
    name: `Week of ${weekStarting.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}`,
    weekStarting,
    status: 'draft',
    meals: overrides.meals || [],
    createdAt: now,
    updatedAt: now,
    ...overrides,
  }
}

/**
 * Creates an empty meal plan (no meals)
 */
export function createEmptyMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  return createMealPlan({
    meals: [],
    status: 'draft',
    ...overrides,
  })
}

/**
 * Creates a meal plan with a full week of meals
 */
export function createFullWeekMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  const plan = createMealPlan(overrides)
  const meals: PlannedMeal[] = []

  for (const day of daysOfWeek as DayOfWeek[]) {
    meals.push(
      createPlannedMeal({ mealPlanId: plan.id, dayOfWeek: day, mealType: 'breakfast', sortOrder: 1 }),
      createPlannedMeal({ mealPlanId: plan.id, dayOfWeek: day, mealType: 'lunch', sortOrder: 2 }),
      createPlannedMeal({ mealPlanId: plan.id, dayOfWeek: day, mealType: 'dinner', sortOrder: 3 })
    )
  }

  plan.meals = meals
  return plan
}

/**
 * Creates a meal plan with batch cooking (leftovers)
 */
export function createBatchCookMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  const plan = createMealPlan(overrides)
  const batchRecipe = createRecipe({ servings: 8, tags: ['batch-cook'] })

  const meals: PlannedMeal[] = [
    // Monday - Cook batch
    createPlannedMeal({
      mealPlanId: plan.id,
      recipe: batchRecipe,
      recipeName: batchRecipe.recipeName,
      recipeId: batchRecipe.id,
      dayOfWeek: 'Monday',
      mealType: 'dinner',
      isLeftover: false,
      batchCookSourceDay: null,
      sortOrder: 1,
    }),
    // Wednesday - Use leftover
    createPlannedMeal({
      mealPlanId: plan.id,
      recipe: batchRecipe,
      recipeName: batchRecipe.recipeName,
      recipeId: batchRecipe.id,
      dayOfWeek: 'Wednesday',
      mealType: 'dinner',
      isLeftover: true,
      batchCookSourceDay: 'Monday',
      sortOrder: 1,
    }),
    // Thursday - Use leftover
    createPlannedMeal({
      mealPlanId: plan.id,
      recipe: batchRecipe,
      recipeName: batchRecipe.recipeName,
      recipeId: batchRecipe.id,
      dayOfWeek: 'Thursday',
      mealType: 'lunch',
      isLeftover: true,
      batchCookSourceDay: 'Monday',
      sortOrder: 1,
    }),
  ]

  plan.meals = meals
  return plan
}

/**
 * Creates a finalized meal plan
 */
export function createFinalizedMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  const plan = createFullWeekMealPlan(overrides)
  plan.status = 'active'
  return plan
}

/**
 * Creates an archived meal plan
 */
export function createArchivedMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  const plan = createFullWeekMealPlan(overrides)
  plan.status = 'archived'
  // Set week starting to 2 weeks ago
  plan.weekStarting = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)
  return plan
}

// ============================================================================
// MEAL PLAN SETTINGS FACTORIES
// ============================================================================

/**
 * Creates default meal plan settings
 */
export function createMealPlanSettings(overrides: Partial<MealPlanSettings> = {}): MealPlanSettings {
  return {
    macroMode: 'balanced',
    varietyEnabled: true,
    dinnerCooldown: 14,
    lunchCooldown: 7,
    breakfastCooldown: 3,
    snackCooldown: 2,
    minCuisines: 3,
    maxSameCuisine: 2,
    shoppingMode: 'moderate',
    expiryPriority: 'moderate',
    expiryWindow: 5,
    useItUpItems: [],
    batchCookingEnabled: true,
    maxLeftoverDays: 4,
    priorityOrder: ['macros', 'ratings', 'variety', 'shopping', 'prep', 'time'],
    feedbackDetail: 'medium',
    ...overrides,
  }
}

/**
 * Creates settings optimized for small recipe libraries
 */
export function createSmallLibrarySettings(): MealPlanSettings {
  return createMealPlanSettings({
    dinnerCooldown: 3,
    lunchCooldown: 2,
    breakfastCooldown: 1,
    snackCooldown: 1,
    varietyEnabled: false,
    minCuisines: 1,
    maxSameCuisine: 5,
  })
}

/**
 * Creates settings for maximum variety
 */
export function createMaxVarietySettings(): MealPlanSettings {
  return createMealPlanSettings({
    dinnerCooldown: 21,
    lunchCooldown: 14,
    breakfastCooldown: 7,
    snackCooldown: 5,
    varietyEnabled: true,
    minCuisines: 5,
    maxSameCuisine: 1,
  })
}

// ============================================================================
// INVALID DATA FACTORIES (for negative tests)
// ============================================================================

export const invalidMealPlans = {
  missingUserId: {
    id: 'invalid-plan-001',
    name: 'No User Plan',
    meals: [],
  },
  invalidStatus: {
    id: 'invalid-plan-002',
    userId: 'user-123',
    name: 'Invalid Status',
    status: 'invalid' as any,
    meals: [],
  },
  pastWeekStart: {
    id: 'invalid-plan-003',
    userId: 'user-123',
    name: 'Past Week',
    weekStarting: new Date('2020-01-01'),
    status: 'draft',
    meals: [],
  },
}

export const invalidMeals = {
  missingRecipe: {
    id: 'invalid-meal-001',
    mealPlanId: 'plan-123',
    dayOfWeek: 'Monday',
    mealType: 'dinner',
    // No recipeId or recipe
  },
  invalidDay: {
    id: 'invalid-meal-002',
    mealPlanId: 'plan-123',
    recipeId: 'recipe-123',
    dayOfWeek: 'Funday' as any,
    mealType: 'dinner',
  },
  invalidMealType: {
    id: 'invalid-meal-003',
    mealPlanId: 'plan-123',
    recipeId: 'recipe-123',
    dayOfWeek: 'Monday',
    mealType: 'brunch' as any,
  },
}

// ============================================================================
// COOLDOWN VIOLATION FACTORIES (for validation tests)
// ============================================================================

/**
 * Creates a meal plan with a cooldown violation
 * Same recipe used twice without proper leftover marking
 */
export function createCooldownViolationMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  const plan = createMealPlan(overrides)
  const recipe = createRecipe()

  plan.meals = [
    createPlannedMeal({
      mealPlanId: plan.id,
      recipe,
      recipeName: recipe.recipeName,
      recipeId: recipe.id,
      dayOfWeek: 'Monday',
      mealType: 'dinner',
      isLeftover: false,
    }),
    createPlannedMeal({
      mealPlanId: plan.id,
      recipe,
      recipeName: recipe.recipeName,
      recipeId: recipe.id,
      dayOfWeek: 'Wednesday',
      mealType: 'dinner',
      isLeftover: false, // NOT marked as leftover - VIOLATION
    }),
  ]

  return plan
}

/**
 * Creates a meal plan with batch cooking error
 * First occurrence marked as leftover (should be false)
 */
export function createBatchCookErrorMealPlan(overrides: Partial<MealPlan> = {}): MealPlan {
  const plan = createMealPlan(overrides)
  const recipe = createRecipe({ servings: 8 })

  plan.meals = [
    createPlannedMeal({
      mealPlanId: plan.id,
      recipe,
      recipeName: recipe.recipeName,
      recipeId: recipe.id,
      dayOfWeek: 'Monday',
      mealType: 'dinner',
      isLeftover: true, // ERROR: First occurrence should NOT be leftover
    }),
    createPlannedMeal({
      mealPlanId: plan.id,
      recipe,
      recipeName: recipe.recipeName,
      recipeId: recipe.id,
      dayOfWeek: 'Wednesday',
      mealType: 'dinner',
      isLeftover: true,
      batchCookSourceDay: 'Monday',
    }),
  ]

  return plan
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Gets the next Monday from today
 */
function getNextMonday(): Date {
  const today = new Date()
  const dayOfWeek = today.getDay()
  const daysUntilMonday = dayOfWeek === 0 ? 1 : 8 - dayOfWeek
  const nextMonday = new Date(today)
  nextMonday.setDate(today.getDate() + daysUntilMonday)
  nextMonday.setHours(0, 0, 0, 0)
  return nextMonday
}

/**
 * Gets a date for a specific day in the current week
 */
export function getDateForDay(day: DayOfWeek, weekStart: Date = getNextMonday()): Date {
  const dayIndex = daysOfWeek.indexOf(day)
  const date = new Date(weekStart)
  date.setDate(weekStart.getDate() + dayIndex)
  return date
}
