/**
 * Recipe Factory
 * Dynamic recipe data generation for tests
 *
 * Generated by Test Builder Agent
 * Date: 2025-12-16
 */

// Simple generators (no faker dependency)
const generateId = () => `recipe-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
const randomInt = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min
const randomFloat = (min: number, max: number, decimals = 1) =>
  parseFloat((Math.random() * (max - min) + min).toFixed(decimals))

// Sample data for realistic recipes
const recipeTitles = [
  'Chicken Stir Fry',
  'Beef Tacos',
  'Vegetable Curry',
  'Salmon Pasta',
  'Mediterranean Salad',
  'Thai Green Curry',
  'Mushroom Risotto',
  'Grilled Chicken',
  'Pasta Bolognese',
  'Fish and Chips',
  'Shepherd\'s Pie',
  'Chicken Tikka Masala',
  'Beef Stroganoff',
  'Prawn Stir Fry',
  'Vegetable Lasagna',
]

const cuisineTypes = ['Italian', 'Mexican', 'Asian', 'British', 'Mediterranean', 'Indian', 'Thai', 'American']
const mealTypes = ['breakfast', 'lunch', 'dinner', 'snack']

const ingredientNames = [
  'Chicken Breast', 'Beef Mince', 'Salmon Fillet', 'Prawns', 'Tofu',
  'Onion', 'Garlic', 'Tomatoes', 'Bell Pepper', 'Mushrooms',
  'Rice', 'Pasta', 'Bread', 'Potatoes', 'Noodles',
  'Olive Oil', 'Soy Sauce', 'Stock', 'Coconut Milk', 'Cream',
  'Salt', 'Pepper', 'Cumin', 'Paprika', 'Oregano',
]

const units = ['g', 'ml', 'piece', 'tbsp', 'tsp', 'cup', 'clove']

// ============================================================================
// RECIPE TYPES
// ============================================================================

export interface RecipeIngredient {
  id: string
  recipeId: string
  ingredientName: string
  quantity: number
  unit: string
  notes: string | null
  sortOrder: number
}

export interface Recipe {
  id: string
  userId: string
  recipeName: string
  description: string | null
  servings: number
  prepTimeMinutes: number
  cookTimeMinutes: number
  totalTimeMinutes: number
  cuisineType: string | null
  mealType: string[]
  caloriesPerServing: number | null
  proteinPerServing: number | null
  carbsPerServing: number | null
  fatPerServing: number | null
  fiberPerServing: number | null
  isVegetarian: boolean
  isVegan: boolean
  isDairyFree: boolean
  isGlutenFree: boolean
  isNutFree: boolean
  tags: string[]
  recipeSource: 'manual' | 'url' | 'photo' | 'text'
  sourceUrl: string | null
  isFavorite: boolean
  timesUsed: number
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  ingredients?: RecipeIngredient[]
  instructions?: string[]
}

// ============================================================================
// INGREDIENT FACTORIES
// ============================================================================

/**
 * Creates a single ingredient
 */
export function createIngredient(overrides: Partial<RecipeIngredient> = {}): RecipeIngredient {
  const name = ingredientNames[randomInt(0, ingredientNames.length - 1)]
  return {
    id: `ing-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    recipeId: overrides.recipeId || generateId(),
    ingredientName: name,
    quantity: randomFloat(50, 500),
    unit: units[randomInt(0, units.length - 1)],
    notes: null,
    sortOrder: overrides.sortOrder || 1,
    ...overrides,
  }
}

/**
 * Creates multiple ingredients
 */
export function createIngredients(count: number, recipeId?: string): RecipeIngredient[] {
  return Array.from({ length: count }, (_, i) =>
    createIngredient({ recipeId, sortOrder: i + 1 })
  )
}

// ============================================================================
// RECIPE FACTORIES
// ============================================================================

/**
 * Creates a test recipe with default or custom values
 */
export function createRecipe(overrides: Partial<Recipe> = {}): Recipe {
  const now = new Date()
  const recipeName = recipeTitles[randomInt(0, recipeTitles.length - 1)]
  const prepTime = randomInt(5, 30)
  const cookTime = randomInt(10, 60)

  const recipe: Recipe = {
    id: generateId(),
    userId: overrides.userId || `user-${Date.now()}`,
    recipeName,
    description: `A delicious ${recipeName.toLowerCase()}`,
    servings: randomInt(2, 6),
    prepTimeMinutes: prepTime,
    cookTimeMinutes: cookTime,
    totalTimeMinutes: prepTime + cookTime,
    cuisineType: cuisineTypes[randomInt(0, cuisineTypes.length - 1)],
    mealType: [mealTypes[randomInt(0, mealTypes.length - 1)]],
    caloriesPerServing: randomInt(300, 700),
    proteinPerServing: randomInt(15, 45),
    carbsPerServing: randomInt(20, 60),
    fatPerServing: randomInt(10, 35),
    fiberPerServing: randomInt(3, 12),
    isVegetarian: Math.random() > 0.7,
    isVegan: Math.random() > 0.9,
    isDairyFree: Math.random() > 0.6,
    isGlutenFree: Math.random() > 0.6,
    isNutFree: Math.random() > 0.8,
    tags: [],
    recipeSource: 'manual',
    sourceUrl: null,
    isFavorite: false,
    timesUsed: 0,
    isActive: true,
    createdAt: now,
    updatedAt: now,
    ...overrides,
  }

  // Add ingredients if not provided
  if (!overrides.ingredients) {
    recipe.ingredients = createIngredients(randomInt(4, 8), recipe.id)
  }

  return recipe
}

/**
 * Creates multiple test recipes
 */
export function createRecipes(count: number, overrides: Partial<Recipe> = {}): Recipe[] {
  return Array.from({ length: count }, () => createRecipe(overrides))
}

// ============================================================================
// SPECIFIC SCENARIOS
// ============================================================================

/**
 * Creates a quick recipe (under 30 mins total)
 */
export function createQuickRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    totalTimeMinutes: 20,
    tags: ['quick', 'easy', 'weeknight'],
    ...overrides,
  })
}

/**
 * Creates a batch cook recipe (large servings)
 */
export function createBatchCookRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    servings: 8,
    tags: ['batch-cook', 'freezer-friendly', 'meal-prep'],
    ...overrides,
  })
}

/**
 * Creates a slow cook recipe (long cook time)
 */
export function createSlowCookRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    prepTimeMinutes: 20,
    cookTimeMinutes: 240,
    totalTimeMinutes: 260,
    tags: ['slow-cooker', 'one-pot'],
    ...overrides,
  })
}

/**
 * Creates a vegetarian recipe
 */
export function createVegetarianRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    isVegetarian: true,
    isVegan: false,
    tags: ['vegetarian'],
    recipeName: 'Vegetable Stir Fry',
    ...overrides,
  })
}

/**
 * Creates a vegan recipe
 */
export function createVeganRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    isVegetarian: true,
    isVegan: true,
    isDairyFree: true,
    tags: ['vegan', 'plant-based'],
    recipeName: 'Tofu Curry',
    ...overrides,
  })
}

/**
 * Creates a high protein recipe
 */
export function createHighProteinRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    proteinPerServing: 45,
    carbsPerServing: 20,
    fatPerServing: 15,
    caloriesPerServing: 400,
    tags: ['high-protein', 'low-carb'],
    recipeName: 'Grilled Chicken Breast',
    ...overrides,
  })
}

/**
 * Creates a recipe imported from URL
 */
export function createImportedRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    recipeSource: 'url',
    sourceUrl: 'https://www.bbcgoodfood.com/recipes/test-recipe',
    ...overrides,
  })
}

/**
 * Creates a favorited recipe
 */
export function createFavoriteRecipe(overrides: Partial<Recipe> = {}): Recipe {
  return createRecipe({
    isFavorite: true,
    timesUsed: randomInt(5, 20),
    ...overrides,
  })
}

// ============================================================================
// INVALID DATA FACTORIES (for negative tests)
// ============================================================================

export const invalidRecipes = {
  missingName: {
    id: 'invalid-recipe-001',
    servings: 4,
    ingredients: [],
  },
  zeroServings: {
    id: 'invalid-recipe-002',
    recipeName: 'Zero Servings Recipe',
    servings: 0,
  },
  negativeServings: {
    id: 'invalid-recipe-003',
    recipeName: 'Negative Servings',
    servings: -2,
  },
  emptyIngredients: {
    id: 'invalid-recipe-004',
    recipeName: 'No Ingredients',
    servings: 4,
    ingredients: [],
  },
  negativeCalories: {
    id: 'invalid-recipe-005',
    recipeName: 'Invalid Calories',
    servings: 4,
    caloriesPerServing: -100,
  },
}

export const invalidIngredients = {
  missingName: {
    id: 'invalid-ing-001',
    quantity: 100,
    unit: 'g',
  },
  zeroQuantity: {
    id: 'invalid-ing-002',
    ingredientName: 'Zero Quantity',
    quantity: 0,
    unit: 'g',
  },
  negativeQuantity: {
    id: 'invalid-ing-003',
    ingredientName: 'Negative Quantity',
    quantity: -50,
    unit: 'g',
  },
}
