/**
 * User Factory
 * Dynamic user data generation for tests
 *
 * Generated by Test Builder Agent
 * Date: 2025-12-16
 */

// Simple ID/string generators (no faker dependency)
const generateId = () => `user-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
const generateEmail = (prefix = 'test') => `${prefix}-${Date.now()}@example.com`
const generateName = () => {
  const firstNames = ['Chris', 'Sarah', 'James', 'Emma', 'Oliver', 'Sophie', 'William', 'Olivia']
  const lastNames = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Davis', 'Miller', 'Wilson']
  return `${firstNames[Math.floor(Math.random() * firstNames.length)]} ${lastNames[Math.floor(Math.random() * lastNames.length)]}`
}

// ============================================================================
// USER TYPES
// ============================================================================

export interface User {
  id: string
  email: string
  name: string
  createdAt: Date
  updatedAt: Date
}

export interface UserCredentials {
  email: string
  password: string
}

export interface UserProfile {
  id: string
  userId: string
  profileName: string
  age: number
  gender: 'male' | 'female' | 'other'
  heightCm: number
  currentWeightKg: number
  targetWeightKg: number | null
  goalType: 'lose' | 'maintain' | 'gain'
  goalTimeframeWeeks: number | null
  activityLevel: 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active'
  dailyCalorieTarget: number
  dailyProteinTarget: number
  dailyCarbsTarget: number
  dailyFatTarget: number
  dailyFiberTarget: number
  macroTrackingEnabled: boolean
  allergies: string[]
  dietaryPreferences: string | null
  foodLikes: string[]
  foodDislikes: string[]
  createdAt: Date
  updatedAt: Date
}

// ============================================================================
// USER FACTORIES
// ============================================================================

/**
 * Creates a test user with default or custom values
 */
export function createUser(overrides: Partial<User> = {}): User {
  const now = new Date()
  return {
    id: generateId(),
    email: generateEmail(),
    name: generateName(),
    createdAt: now,
    updatedAt: now,
    ...overrides,
  }
}

/**
 * Creates multiple test users
 */
export function createUsers(count: number, overrides: Partial<User> = {}): User[] {
  return Array.from({ length: count }, () => createUser(overrides))
}

/**
 * Creates valid user credentials
 */
export function createCredentials(overrides: Partial<UserCredentials> = {}): UserCredentials {
  return {
    email: generateEmail(),
    password: 'ValidPassword123!',
    ...overrides,
  }
}

/**
 * Creates a user profile with default or custom values
 */
export function createProfile(overrides: Partial<UserProfile> = {}): UserProfile {
  const now = new Date()
  return {
    id: `profile-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    userId: overrides.userId || generateId(),
    profileName: generateName().split(' ')[0], // Just first name
    age: Math.floor(Math.random() * 50) + 18,
    gender: 'male',
    heightCm: Math.floor(Math.random() * 40) + 150,
    currentWeightKg: Math.floor(Math.random() * 50) + 50,
    targetWeightKg: null,
    goalType: 'maintain',
    goalTimeframeWeeks: null,
    activityLevel: 'moderate',
    dailyCalorieTarget: 2000,
    dailyProteinTarget: 150,
    dailyCarbsTarget: 200,
    dailyFatTarget: 70,
    dailyFiberTarget: 30,
    macroTrackingEnabled: true,
    allergies: [],
    dietaryPreferences: null,
    foodLikes: [],
    foodDislikes: [],
    createdAt: now,
    updatedAt: now,
    ...overrides,
  }
}

// ============================================================================
// SPECIFIC SCENARIOS
// ============================================================================

/**
 * Creates an admin user
 */
export function createAdminUser(): User {
  return createUser({
    email: `admin-${Date.now()}@example.com`,
    name: 'Admin User',
  })
}

/**
 * Creates a user with weight loss goal
 */
export function createWeightLossProfile(userId?: string): UserProfile {
  return createProfile({
    userId,
    goalType: 'lose',
    currentWeightKg: 85,
    targetWeightKg: 75,
    goalTimeframeWeeks: 12,
    dailyCalorieTarget: 1800,
  })
}

/**
 * Creates a user with allergies
 */
export function createAllergyProfile(userId?: string, allergies: string[] = ['nuts', 'dairy']): UserProfile {
  return createProfile({
    userId,
    allergies,
    dietaryPreferences: null,
  })
}

/**
 * Creates a vegetarian user profile
 */
export function createVegetarianProfile(userId?: string): UserProfile {
  return createProfile({
    userId,
    dietaryPreferences: 'vegetarian',
    foodDislikes: ['meat', 'fish', 'chicken'],
  })
}

/**
 * Creates credentials for E2E test user (consistent)
 */
export function createE2ETestCredentials(): UserCredentials {
  return {
    email: 'e2e-test@familymealplanner.com',
    password: 'E2ETestPassword123!',
  }
}

// ============================================================================
// INVALID DATA FACTORIES (for negative tests)
// ============================================================================

export const invalidUsers = {
  missingEmail: {
    id: 'invalid-user-001',
    name: 'No Email User',
  },
  invalidEmail: {
    id: 'invalid-user-002',
    email: 'not-an-email',
    name: 'Invalid Email User',
  },
  emptyName: {
    id: 'invalid-user-003',
    email: 'empty@example.com',
    name: '',
  },
}

export const invalidCredentials = {
  missingEmail: { password: 'ValidPassword123!' },
  missingPassword: { email: 'test@example.com' },
  invalidEmail: { email: 'not-an-email', password: 'ValidPassword123!' },
  weakPassword: { email: 'test@example.com', password: '123' },
  emptyPassword: { email: 'test@example.com', password: '' },
}
