/**
 * Test Fixtures Index
 * Re-exports all fixtures, factories, and seeders for convenient importing
 *
 * Generated by Test Builder Agent
 * Date: 2025-12-16
 *
 * Usage:
 *   import { testRecipes, createUser, seedTestUser } from '../fixtures'
 */

// ============================================================================
// EXISTING TEST DATA (from test-data.ts)
// ============================================================================

export {
  // Meal Plan Test Data
  testMealPlanSettings,
  testMealsValid,
  testMealsCooldownViolation,
  testMealsBatchCookingError,
  testRecipeHistory,

  // Inventory Test Data
  testInventoryItems,
  testInventoryItemWithExpiry,

  // Staples Test Data
  testStaples,

  // Recipe Test Data
  testRecipes,
  testRecipeIngredients,

  // Nutrition Test Data
  testNutritionData,

  // Profile Test Data
  testProfiles,

  // Unit Conversion Test Data
  testUnitConversions,

  // Ingredient Normalization Test Data
  testIngredientNormalization,
} from './test-data'

// ============================================================================
// FACTORIES
// ============================================================================

// User Factory
export {
  createUser,
  createUsers,
  createCredentials,
  createProfile,
  createAdminUser,
  createWeightLossProfile,
  createAllergyProfile,
  createVegetarianProfile,
  createE2ETestCredentials,
  invalidUsers,
  invalidCredentials,
  type User,
  type UserCredentials,
  type UserProfile,
} from '../factories/userFactory'

// Recipe Factory
export {
  createIngredient,
  createIngredients,
  createRecipe,
  createRecipes,
  createQuickRecipe,
  createBatchCookRecipe,
  createSlowCookRecipe,
  createVegetarianRecipe,
  createVeganRecipe,
  createHighProteinRecipe,
  createImportedRecipe,
  createFavoriteRecipe,
  invalidRecipes,
  invalidIngredients,
  type Recipe,
  type RecipeIngredient,
} from '../factories/recipeFactory'

// Meal Plan Factory
export {
  createPlannedMeal,
  createDayMeals,
  createMealPlan,
  createEmptyMealPlan,
  createFullWeekMealPlan,
  createBatchCookMealPlan,
  createFinalizedMealPlan,
  createArchivedMealPlan,
  createMealPlanSettings,
  createSmallLibrarySettings,
  createMaxVarietySettings,
  createCooldownViolationMealPlan,
  createBatchCookErrorMealPlan,
  getDateForDay,
  invalidMealPlans,
  invalidMeals,
  type PlannedMeal,
  type MealPlan,
  type MealPlanSettings,
  type DayOfWeek,
  type MealType,
} from '../factories/mealPlanFactory'

// ============================================================================
// SEEDERS (commented out - these require @supabase/supabase-js which is not installed)
// To use seeders, install: npm install @supabase/supabase-js
// Then uncomment the exports below
// ============================================================================

// export {
//   E2E_TEST_USER,
//   seedTestUser,
//   seedTestRecipes as seedTestRecipesForUser,
//   cleanupTestUser,
//   cleanupAllTestData,
//   cleanupTestRecipes as cleanupE2ETestRecipes,
// } from './seeders/authSeeder'

// export {
//   seedTestRecipes,
//   seedMinimalRecipes,
//   cleanupTestRecipes,
//   cleanupUserRecipes,
// } from './seeders/recipeSeeder'

// ============================================================================
// API TEST HELPERS (re-exported for convenience)
// ============================================================================

export {
  createMockRequest,
  createAuthenticatedRequest,
  parseJsonResponse,
  createMockSession,
  mockGetServerSession,
  createRouteContext,
  testDataFactories,
  apiAssertions,
  type ApiResponse,
  type MockSession,
} from '../helpers/api-test-helpers'
